// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/hospede.proto

package br.quixada.ufc.si.classProto;

public final class HospedeProtos {
  private HospedeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HospedeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Hospede)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string cpf = 2;</code>
     * @return Whether the cpf field is set.
     */
    boolean hasCpf();
    /**
     * <code>optional string cpf = 2;</code>
     * @return The cpf.
     */
    java.lang.String getCpf();
    /**
     * <code>optional string cpf = 2;</code>
     * @return The bytes for cpf.
     */
    com.google.protobuf.ByteString
        getCpfBytes();

    /**
     * <code>optional string email = 3;</code>
     * @return Whether the email field is set.
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional string telefone = 4;</code>
     * @return Whether the telefone field is set.
     */
    boolean hasTelefone();
    /**
     * <code>optional string telefone = 4;</code>
     * @return The telefone.
     */
    java.lang.String getTelefone();
    /**
     * <code>optional string telefone = 4;</code>
     * @return The bytes for telefone.
     */
    com.google.protobuf.ByteString
        getTelefoneBytes();

    /**
     * <code>optional string dataNasc = 5;</code>
     * @return Whether the dataNasc field is set.
     */
    boolean hasDataNasc();
    /**
     * <code>optional string dataNasc = 5;</code>
     * @return The dataNasc.
     */
    java.lang.String getDataNasc();
    /**
     * <code>optional string dataNasc = 5;</code>
     * @return The bytes for dataNasc.
     */
    com.google.protobuf.ByteString
        getDataNascBytes();

    /**
     * <code>optional double servicoQuarto = 6;</code>
     * @return Whether the servicoQuarto field is set.
     */
    boolean hasServicoQuarto();
    /**
     * <code>optional double servicoQuarto = 6;</code>
     * @return The servicoQuarto.
     */
    double getServicoQuarto();

    /**
     * <code>optional double aluguel = 7;</code>
     * @return Whether the aluguel field is set.
     */
    boolean hasAluguel();
    /**
     * <code>optional double aluguel = 7;</code>
     * @return The aluguel.
     */
    double getAluguel();
  }
  /**
   * Protobuf type {@code tutorial.Hospede}
   */
  public static final class Hospede extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Hospede)
      HospedeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hospede.newBuilder() to construct.
    private Hospede(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hospede() {
      name_ = "";
      cpf_ = "";
      email_ = "";
      telefone_ = "";
      dataNasc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Hospede();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hospede(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              cpf_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              email_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              telefone_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              dataNasc_ = bs;
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              servicoQuarto_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              aluguel_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.quixada.ufc.si.classProto.HospedeProtos.internal_static_tutorial_Hospede_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.quixada.ufc.si.classProto.HospedeProtos.internal_static_tutorial_Hospede_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.quixada.ufc.si.classProto.HospedeProtos.Hospede.class, br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPF_FIELD_NUMBER = 2;
    private volatile java.lang.Object cpf_;
    /**
     * <code>optional string cpf = 2;</code>
     * @return Whether the cpf field is set.
     */
    @java.lang.Override
    public boolean hasCpf() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string cpf = 2;</code>
     * @return The cpf.
     */
    @java.lang.Override
    public java.lang.String getCpf() {
      java.lang.Object ref = cpf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cpf_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cpf = 2;</code>
     * @return The bytes for cpf.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCpfBytes() {
      java.lang.Object ref = cpf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     * @return Whether the email field is set.
     */
    @java.lang.Override
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TELEFONE_FIELD_NUMBER = 4;
    private volatile java.lang.Object telefone_;
    /**
     * <code>optional string telefone = 4;</code>
     * @return Whether the telefone field is set.
     */
    @java.lang.Override
    public boolean hasTelefone() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string telefone = 4;</code>
     * @return The telefone.
     */
    @java.lang.Override
    public java.lang.String getTelefone() {
      java.lang.Object ref = telefone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          telefone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string telefone = 4;</code>
     * @return The bytes for telefone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTelefoneBytes() {
      java.lang.Object ref = telefone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        telefone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATANASC_FIELD_NUMBER = 5;
    private volatile java.lang.Object dataNasc_;
    /**
     * <code>optional string dataNasc = 5;</code>
     * @return Whether the dataNasc field is set.
     */
    @java.lang.Override
    public boolean hasDataNasc() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string dataNasc = 5;</code>
     * @return The dataNasc.
     */
    @java.lang.Override
    public java.lang.String getDataNasc() {
      java.lang.Object ref = dataNasc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataNasc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dataNasc = 5;</code>
     * @return The bytes for dataNasc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataNascBytes() {
      java.lang.Object ref = dataNasc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataNasc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICOQUARTO_FIELD_NUMBER = 6;
    private double servicoQuarto_;
    /**
     * <code>optional double servicoQuarto = 6;</code>
     * @return Whether the servicoQuarto field is set.
     */
    @java.lang.Override
    public boolean hasServicoQuarto() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional double servicoQuarto = 6;</code>
     * @return The servicoQuarto.
     */
    @java.lang.Override
    public double getServicoQuarto() {
      return servicoQuarto_;
    }

    public static final int ALUGUEL_FIELD_NUMBER = 7;
    private double aluguel_;
    /**
     * <code>optional double aluguel = 7;</code>
     * @return Whether the aluguel field is set.
     */
    @java.lang.Override
    public boolean hasAluguel() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional double aluguel = 7;</code>
     * @return The aluguel.
     */
    @java.lang.Override
    public double getAluguel() {
      return aluguel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cpf_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, telefone_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dataNasc_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeDouble(6, servicoQuarto_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeDouble(7, aluguel_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cpf_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, telefone_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dataNasc_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, servicoQuarto_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, aluguel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.quixada.ufc.si.classProto.HospedeProtos.Hospede)) {
        return super.equals(obj);
      }
      br.quixada.ufc.si.classProto.HospedeProtos.Hospede other = (br.quixada.ufc.si.classProto.HospedeProtos.Hospede) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasCpf() != other.hasCpf()) return false;
      if (hasCpf()) {
        if (!getCpf()
            .equals(other.getCpf())) return false;
      }
      if (hasEmail() != other.hasEmail()) return false;
      if (hasEmail()) {
        if (!getEmail()
            .equals(other.getEmail())) return false;
      }
      if (hasTelefone() != other.hasTelefone()) return false;
      if (hasTelefone()) {
        if (!getTelefone()
            .equals(other.getTelefone())) return false;
      }
      if (hasDataNasc() != other.hasDataNasc()) return false;
      if (hasDataNasc()) {
        if (!getDataNasc()
            .equals(other.getDataNasc())) return false;
      }
      if (hasServicoQuarto() != other.hasServicoQuarto()) return false;
      if (hasServicoQuarto()) {
        if (java.lang.Double.doubleToLongBits(getServicoQuarto())
            != java.lang.Double.doubleToLongBits(
                other.getServicoQuarto())) return false;
      }
      if (hasAluguel() != other.hasAluguel()) return false;
      if (hasAluguel()) {
        if (java.lang.Double.doubleToLongBits(getAluguel())
            != java.lang.Double.doubleToLongBits(
                other.getAluguel())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasCpf()) {
        hash = (37 * hash) + CPF_FIELD_NUMBER;
        hash = (53 * hash) + getCpf().hashCode();
      }
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      if (hasTelefone()) {
        hash = (37 * hash) + TELEFONE_FIELD_NUMBER;
        hash = (53 * hash) + getTelefone().hashCode();
      }
      if (hasDataNasc()) {
        hash = (37 * hash) + DATANASC_FIELD_NUMBER;
        hash = (53 * hash) + getDataNasc().hashCode();
      }
      if (hasServicoQuarto()) {
        hash = (37 * hash) + SERVICOQUARTO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getServicoQuarto()));
      }
      if (hasAluguel()) {
        hash = (37 * hash) + ALUGUEL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getAluguel()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.quixada.ufc.si.classProto.HospedeProtos.Hospede prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Hospede}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Hospede)
        br.quixada.ufc.si.classProto.HospedeProtos.HospedeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.quixada.ufc.si.classProto.HospedeProtos.internal_static_tutorial_Hospede_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.quixada.ufc.si.classProto.HospedeProtos.internal_static_tutorial_Hospede_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.quixada.ufc.si.classProto.HospedeProtos.Hospede.class, br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder.class);
      }

      // Construct using br.quixada.ufc.si.classProto.HospedeProtos.Hospede.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cpf_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        telefone_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        dataNasc_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        servicoQuarto_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        aluguel_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.quixada.ufc.si.classProto.HospedeProtos.internal_static_tutorial_Hospede_descriptor;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.HospedeProtos.Hospede getDefaultInstanceForType() {
        return br.quixada.ufc.si.classProto.HospedeProtos.Hospede.getDefaultInstance();
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.HospedeProtos.Hospede build() {
        br.quixada.ufc.si.classProto.HospedeProtos.Hospede result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.HospedeProtos.Hospede buildPartial() {
        br.quixada.ufc.si.classProto.HospedeProtos.Hospede result = new br.quixada.ufc.si.classProto.HospedeProtos.Hospede(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cpf_ = cpf_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.telefone_ = telefone_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dataNasc_ = dataNasc_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.servicoQuarto_ = servicoQuarto_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.aluguel_ = aluguel_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.quixada.ufc.si.classProto.HospedeProtos.Hospede) {
          return mergeFrom((br.quixada.ufc.si.classProto.HospedeProtos.Hospede)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.quixada.ufc.si.classProto.HospedeProtos.Hospede other) {
        if (other == br.quixada.ufc.si.classProto.HospedeProtos.Hospede.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCpf()) {
          bitField0_ |= 0x00000002;
          cpf_ = other.cpf_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasTelefone()) {
          bitField0_ |= 0x00000008;
          telefone_ = other.telefone_;
          onChanged();
        }
        if (other.hasDataNasc()) {
          bitField0_ |= 0x00000010;
          dataNasc_ = other.dataNasc_;
          onChanged();
        }
        if (other.hasServicoQuarto()) {
          setServicoQuarto(other.getServicoQuarto());
        }
        if (other.hasAluguel()) {
          setAluguel(other.getAluguel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.quixada.ufc.si.classProto.HospedeProtos.Hospede parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.quixada.ufc.si.classProto.HospedeProtos.Hospede) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cpf_ = "";
      /**
       * <code>optional string cpf = 2;</code>
       * @return Whether the cpf field is set.
       */
      public boolean hasCpf() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string cpf = 2;</code>
       * @return The cpf.
       */
      public java.lang.String getCpf() {
        java.lang.Object ref = cpf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cpf_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cpf = 2;</code>
       * @return The bytes for cpf.
       */
      public com.google.protobuf.ByteString
          getCpfBytes() {
        java.lang.Object ref = cpf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cpf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cpf = 2;</code>
       * @param value The cpf to set.
       * @return This builder for chaining.
       */
      public Builder setCpf(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cpf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cpf = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpf() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cpf_ = getDefaultInstance().getCpf();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cpf = 2;</code>
       * @param value The bytes for cpf to set.
       * @return This builder for chaining.
       */
      public Builder setCpfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cpf_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       * @return Whether the email field is set.
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object telefone_ = "";
      /**
       * <code>optional string telefone = 4;</code>
       * @return Whether the telefone field is set.
       */
      public boolean hasTelefone() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string telefone = 4;</code>
       * @return The telefone.
       */
      public java.lang.String getTelefone() {
        java.lang.Object ref = telefone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            telefone_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string telefone = 4;</code>
       * @return The bytes for telefone.
       */
      public com.google.protobuf.ByteString
          getTelefoneBytes() {
        java.lang.Object ref = telefone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          telefone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string telefone = 4;</code>
       * @param value The telefone to set.
       * @return This builder for chaining.
       */
      public Builder setTelefone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        telefone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string telefone = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTelefone() {
        bitField0_ = (bitField0_ & ~0x00000008);
        telefone_ = getDefaultInstance().getTelefone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string telefone = 4;</code>
       * @param value The bytes for telefone to set.
       * @return This builder for chaining.
       */
      public Builder setTelefoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        telefone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataNasc_ = "";
      /**
       * <code>optional string dataNasc = 5;</code>
       * @return Whether the dataNasc field is set.
       */
      public boolean hasDataNasc() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string dataNasc = 5;</code>
       * @return The dataNasc.
       */
      public java.lang.String getDataNasc() {
        java.lang.Object ref = dataNasc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataNasc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dataNasc = 5;</code>
       * @return The bytes for dataNasc.
       */
      public com.google.protobuf.ByteString
          getDataNascBytes() {
        java.lang.Object ref = dataNasc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataNasc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dataNasc = 5;</code>
       * @param value The dataNasc to set.
       * @return This builder for chaining.
       */
      public Builder setDataNasc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dataNasc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataNasc = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataNasc() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dataNasc_ = getDefaultInstance().getDataNasc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataNasc = 5;</code>
       * @param value The bytes for dataNasc to set.
       * @return This builder for chaining.
       */
      public Builder setDataNascBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dataNasc_ = value;
        onChanged();
        return this;
      }

      private double servicoQuarto_ ;
      /**
       * <code>optional double servicoQuarto = 6;</code>
       * @return Whether the servicoQuarto field is set.
       */
      @java.lang.Override
      public boolean hasServicoQuarto() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional double servicoQuarto = 6;</code>
       * @return The servicoQuarto.
       */
      @java.lang.Override
      public double getServicoQuarto() {
        return servicoQuarto_;
      }
      /**
       * <code>optional double servicoQuarto = 6;</code>
       * @param value The servicoQuarto to set.
       * @return This builder for chaining.
       */
      public Builder setServicoQuarto(double value) {
        bitField0_ |= 0x00000020;
        servicoQuarto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double servicoQuarto = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearServicoQuarto() {
        bitField0_ = (bitField0_ & ~0x00000020);
        servicoQuarto_ = 0D;
        onChanged();
        return this;
      }

      private double aluguel_ ;
      /**
       * <code>optional double aluguel = 7;</code>
       * @return Whether the aluguel field is set.
       */
      @java.lang.Override
      public boolean hasAluguel() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional double aluguel = 7;</code>
       * @return The aluguel.
       */
      @java.lang.Override
      public double getAluguel() {
        return aluguel_;
      }
      /**
       * <code>optional double aluguel = 7;</code>
       * @param value The aluguel to set.
       * @return This builder for chaining.
       */
      public Builder setAluguel(double value) {
        bitField0_ |= 0x00000040;
        aluguel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double aluguel = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAluguel() {
        bitField0_ = (bitField0_ & ~0x00000040);
        aluguel_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Hospede)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Hospede)
    private static final br.quixada.ufc.si.classProto.HospedeProtos.Hospede DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.quixada.ufc.si.classProto.HospedeProtos.Hospede();
    }

    public static br.quixada.ufc.si.classProto.HospedeProtos.Hospede getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Hospede>
        PARSER = new com.google.protobuf.AbstractParser<Hospede>() {
      @java.lang.Override
      public Hospede parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hospede(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hospede> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hospede> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.quixada.ufc.si.classProto.HospedeProtos.Hospede getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HospedeBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.HospedeBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tutorial.Hospede hospede = 1;</code>
     */
    java.util.List<br.quixada.ufc.si.classProto.HospedeProtos.Hospede> 
        getHospedeList();
    /**
     * <code>repeated .tutorial.Hospede hospede = 1;</code>
     */
    br.quixada.ufc.si.classProto.HospedeProtos.Hospede getHospede(int index);
    /**
     * <code>repeated .tutorial.Hospede hospede = 1;</code>
     */
    int getHospedeCount();
    /**
     * <code>repeated .tutorial.Hospede hospede = 1;</code>
     */
    java.util.List<? extends br.quixada.ufc.si.classProto.HospedeProtos.HospedeOrBuilder> 
        getHospedeOrBuilderList();
    /**
     * <code>repeated .tutorial.Hospede hospede = 1;</code>
     */
    br.quixada.ufc.si.classProto.HospedeProtos.HospedeOrBuilder getHospedeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.HospedeBook}
   */
  public static final class HospedeBook extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.HospedeBook)
      HospedeBookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HospedeBook.newBuilder() to construct.
    private HospedeBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HospedeBook() {
      hospede_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HospedeBook();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HospedeBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                hospede_ = new java.util.ArrayList<br.quixada.ufc.si.classProto.HospedeProtos.Hospede>();
                mutable_bitField0_ |= 0x00000001;
              }
              hospede_.add(
                  input.readMessage(br.quixada.ufc.si.classProto.HospedeProtos.Hospede.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          hospede_ = java.util.Collections.unmodifiableList(hospede_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.quixada.ufc.si.classProto.HospedeProtos.internal_static_tutorial_HospedeBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.quixada.ufc.si.classProto.HospedeProtos.internal_static_tutorial_HospedeBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook.class, br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook.Builder.class);
    }

    public static final int HOSPEDE_FIELD_NUMBER = 1;
    private java.util.List<br.quixada.ufc.si.classProto.HospedeProtos.Hospede> hospede_;
    /**
     * <code>repeated .tutorial.Hospede hospede = 1;</code>
     */
    @java.lang.Override
    public java.util.List<br.quixada.ufc.si.classProto.HospedeProtos.Hospede> getHospedeList() {
      return hospede_;
    }
    /**
     * <code>repeated .tutorial.Hospede hospede = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends br.quixada.ufc.si.classProto.HospedeProtos.HospedeOrBuilder> 
        getHospedeOrBuilderList() {
      return hospede_;
    }
    /**
     * <code>repeated .tutorial.Hospede hospede = 1;</code>
     */
    @java.lang.Override
    public int getHospedeCount() {
      return hospede_.size();
    }
    /**
     * <code>repeated .tutorial.Hospede hospede = 1;</code>
     */
    @java.lang.Override
    public br.quixada.ufc.si.classProto.HospedeProtos.Hospede getHospede(int index) {
      return hospede_.get(index);
    }
    /**
     * <code>repeated .tutorial.Hospede hospede = 1;</code>
     */
    @java.lang.Override
    public br.quixada.ufc.si.classProto.HospedeProtos.HospedeOrBuilder getHospedeOrBuilder(
        int index) {
      return hospede_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < hospede_.size(); i++) {
        output.writeMessage(1, hospede_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < hospede_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, hospede_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook)) {
        return super.equals(obj);
      }
      br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook other = (br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook) obj;

      if (!getHospedeList()
          .equals(other.getHospedeList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHospedeCount() > 0) {
        hash = (37 * hash) + HOSPEDE_FIELD_NUMBER;
        hash = (53 * hash) + getHospedeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.HospedeBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.HospedeBook)
        br.quixada.ufc.si.classProto.HospedeProtos.HospedeBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.quixada.ufc.si.classProto.HospedeProtos.internal_static_tutorial_HospedeBook_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.quixada.ufc.si.classProto.HospedeProtos.internal_static_tutorial_HospedeBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook.class, br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook.Builder.class);
      }

      // Construct using br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHospedeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (hospedeBuilder_ == null) {
          hospede_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          hospedeBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.quixada.ufc.si.classProto.HospedeProtos.internal_static_tutorial_HospedeBook_descriptor;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook getDefaultInstanceForType() {
        return br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook.getDefaultInstance();
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook build() {
        br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook buildPartial() {
        br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook result = new br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook(this);
        int from_bitField0_ = bitField0_;
        if (hospedeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            hospede_ = java.util.Collections.unmodifiableList(hospede_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.hospede_ = hospede_;
        } else {
          result.hospede_ = hospedeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook) {
          return mergeFrom((br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook other) {
        if (other == br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook.getDefaultInstance()) return this;
        if (hospedeBuilder_ == null) {
          if (!other.hospede_.isEmpty()) {
            if (hospede_.isEmpty()) {
              hospede_ = other.hospede_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHospedeIsMutable();
              hospede_.addAll(other.hospede_);
            }
            onChanged();
          }
        } else {
          if (!other.hospede_.isEmpty()) {
            if (hospedeBuilder_.isEmpty()) {
              hospedeBuilder_.dispose();
              hospedeBuilder_ = null;
              hospede_ = other.hospede_;
              bitField0_ = (bitField0_ & ~0x00000001);
              hospedeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHospedeFieldBuilder() : null;
            } else {
              hospedeBuilder_.addAllMessages(other.hospede_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<br.quixada.ufc.si.classProto.HospedeProtos.Hospede> hospede_ =
        java.util.Collections.emptyList();
      private void ensureHospedeIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          hospede_ = new java.util.ArrayList<br.quixada.ufc.si.classProto.HospedeProtos.Hospede>(hospede_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.quixada.ufc.si.classProto.HospedeProtos.Hospede, br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder, br.quixada.ufc.si.classProto.HospedeProtos.HospedeOrBuilder> hospedeBuilder_;

      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public java.util.List<br.quixada.ufc.si.classProto.HospedeProtos.Hospede> getHospedeList() {
        if (hospedeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hospede_);
        } else {
          return hospedeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public int getHospedeCount() {
        if (hospedeBuilder_ == null) {
          return hospede_.size();
        } else {
          return hospedeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public br.quixada.ufc.si.classProto.HospedeProtos.Hospede getHospede(int index) {
        if (hospedeBuilder_ == null) {
          return hospede_.get(index);
        } else {
          return hospedeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public Builder setHospede(
          int index, br.quixada.ufc.si.classProto.HospedeProtos.Hospede value) {
        if (hospedeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHospedeIsMutable();
          hospede_.set(index, value);
          onChanged();
        } else {
          hospedeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public Builder setHospede(
          int index, br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder builderForValue) {
        if (hospedeBuilder_ == null) {
          ensureHospedeIsMutable();
          hospede_.set(index, builderForValue.build());
          onChanged();
        } else {
          hospedeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public Builder addHospede(br.quixada.ufc.si.classProto.HospedeProtos.Hospede value) {
        if (hospedeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHospedeIsMutable();
          hospede_.add(value);
          onChanged();
        } else {
          hospedeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public Builder addHospede(
          int index, br.quixada.ufc.si.classProto.HospedeProtos.Hospede value) {
        if (hospedeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHospedeIsMutable();
          hospede_.add(index, value);
          onChanged();
        } else {
          hospedeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public Builder addHospede(
          br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder builderForValue) {
        if (hospedeBuilder_ == null) {
          ensureHospedeIsMutable();
          hospede_.add(builderForValue.build());
          onChanged();
        } else {
          hospedeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public Builder addHospede(
          int index, br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder builderForValue) {
        if (hospedeBuilder_ == null) {
          ensureHospedeIsMutable();
          hospede_.add(index, builderForValue.build());
          onChanged();
        } else {
          hospedeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public Builder addAllHospede(
          java.lang.Iterable<? extends br.quixada.ufc.si.classProto.HospedeProtos.Hospede> values) {
        if (hospedeBuilder_ == null) {
          ensureHospedeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hospede_);
          onChanged();
        } else {
          hospedeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public Builder clearHospede() {
        if (hospedeBuilder_ == null) {
          hospede_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          hospedeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public Builder removeHospede(int index) {
        if (hospedeBuilder_ == null) {
          ensureHospedeIsMutable();
          hospede_.remove(index);
          onChanged();
        } else {
          hospedeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder getHospedeBuilder(
          int index) {
        return getHospedeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public br.quixada.ufc.si.classProto.HospedeProtos.HospedeOrBuilder getHospedeOrBuilder(
          int index) {
        if (hospedeBuilder_ == null) {
          return hospede_.get(index);  } else {
          return hospedeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public java.util.List<? extends br.quixada.ufc.si.classProto.HospedeProtos.HospedeOrBuilder> 
           getHospedeOrBuilderList() {
        if (hospedeBuilder_ != null) {
          return hospedeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hospede_);
        }
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder addHospedeBuilder() {
        return getHospedeFieldBuilder().addBuilder(
            br.quixada.ufc.si.classProto.HospedeProtos.Hospede.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder addHospedeBuilder(
          int index) {
        return getHospedeFieldBuilder().addBuilder(
            index, br.quixada.ufc.si.classProto.HospedeProtos.Hospede.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Hospede hospede = 1;</code>
       */
      public java.util.List<br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder> 
           getHospedeBuilderList() {
        return getHospedeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.quixada.ufc.si.classProto.HospedeProtos.Hospede, br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder, br.quixada.ufc.si.classProto.HospedeProtos.HospedeOrBuilder> 
          getHospedeFieldBuilder() {
        if (hospedeBuilder_ == null) {
          hospedeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              br.quixada.ufc.si.classProto.HospedeProtos.Hospede, br.quixada.ufc.si.classProto.HospedeProtos.Hospede.Builder, br.quixada.ufc.si.classProto.HospedeProtos.HospedeOrBuilder>(
                  hospede_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          hospede_ = null;
        }
        return hospedeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.HospedeBook)
    }

    // @@protoc_insertion_point(class_scope:tutorial.HospedeBook)
    private static final br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook();
    }

    public static br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HospedeBook>
        PARSER = new com.google.protobuf.AbstractParser<HospedeBook>() {
      @java.lang.Override
      public HospedeBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HospedeBook(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HospedeBook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HospedeBook> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.quixada.ufc.si.classProto.HospedeProtos.HospedeBook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Hospede_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Hospede_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_HospedeBook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_HospedeBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/hospede.proto\022\010tutorial\"\177\n\007Hospe" +
      "de\022\014\n\004name\030\001 \001(\t\022\013\n\003cpf\030\002 \001(\t\022\r\n\005email\030\003" +
      " \001(\t\022\020\n\010telefone\030\004 \001(\t\022\020\n\010dataNasc\030\005 \001(\t" +
      "\022\025\n\rservicoQuarto\030\006 \001(\001\022\017\n\007aluguel\030\007 \001(\001" +
      "\"1\n\013HospedeBook\022\"\n\007hospede\030\001 \003(\0132\021.tutor" +
      "ial.HospedeB-\n\034br.quixada.ufc.si.classPr" +
      "otoB\rHospedeProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Hospede_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Hospede_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Hospede_descriptor,
        new java.lang.String[] { "Name", "Cpf", "Email", "Telefone", "DataNasc", "ServicoQuarto", "Aluguel", });
    internal_static_tutorial_HospedeBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_HospedeBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_HospedeBook_descriptor,
        new java.lang.String[] { "Hospede", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
