// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/message.proto

package br.quixada.ufc.si.classProto;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>optional int32 id = 2;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>optional string obfReference = 3;</code>
     * @return Whether the obfReference field is set.
     */
    boolean hasObfReference();
    /**
     * <code>optional string obfReference = 3;</code>
     * @return The obfReference.
     */
    java.lang.String getObfReference();
    /**
     * <code>optional string obfReference = 3;</code>
     * @return The bytes for obfReference.
     */
    com.google.protobuf.ByteString
        getObfReferenceBytes();

    /**
     * <code>optional string methodId = 4;</code>
     * @return Whether the methodId field is set.
     */
    boolean hasMethodId();
    /**
     * <code>optional string methodId = 4;</code>
     * @return The methodId.
     */
    java.lang.String getMethodId();
    /**
     * <code>optional string methodId = 4;</code>
     * @return The bytes for methodId.
     */
    com.google.protobuf.ByteString
        getMethodIdBytes();

    /**
     * <code>optional bytes arguments = 5;</code>
     * @return Whether the arguments field is set.
     */
    boolean hasArguments();
    /**
     * <code>optional bytes arguments = 5;</code>
     * @return The arguments.
     */
    com.google.protobuf.ByteString getArguments();
  }
  /**
   * Protobuf type {@code tutorial.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      obfReference_ = "";
      methodId_ = "";
      arguments_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              obfReference_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              methodId_ = bs;
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              arguments_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.quixada.ufc.si.classProto.MessageProtos.internal_static_tutorial_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.quixada.ufc.si.classProto.MessageProtos.internal_static_tutorial_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.quixada.ufc.si.classProto.MessageProtos.Message.class, br.quixada.ufc.si.classProto.MessageProtos.Message.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional int32 type = 1;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int OBFREFERENCE_FIELD_NUMBER = 3;
    private volatile java.lang.Object obfReference_;
    /**
     * <code>optional string obfReference = 3;</code>
     * @return Whether the obfReference field is set.
     */
    @java.lang.Override
    public boolean hasObfReference() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string obfReference = 3;</code>
     * @return The obfReference.
     */
    @java.lang.Override
    public java.lang.String getObfReference() {
      java.lang.Object ref = obfReference_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          obfReference_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string obfReference = 3;</code>
     * @return The bytes for obfReference.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getObfReferenceBytes() {
      java.lang.Object ref = obfReference_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        obfReference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODID_FIELD_NUMBER = 4;
    private volatile java.lang.Object methodId_;
    /**
     * <code>optional string methodId = 4;</code>
     * @return Whether the methodId field is set.
     */
    @java.lang.Override
    public boolean hasMethodId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string methodId = 4;</code>
     * @return The methodId.
     */
    @java.lang.Override
    public java.lang.String getMethodId() {
      java.lang.Object ref = methodId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string methodId = 4;</code>
     * @return The bytes for methodId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodIdBytes() {
      java.lang.Object ref = methodId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGUMENTS_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString arguments_;
    /**
     * <code>optional bytes arguments = 5;</code>
     * @return Whether the arguments field is set.
     */
    @java.lang.Override
    public boolean hasArguments() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bytes arguments = 5;</code>
     * @return The arguments.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getArguments() {
      return arguments_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, obfReference_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, methodId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBytes(5, arguments_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, obfReference_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, methodId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, arguments_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.quixada.ufc.si.classProto.MessageProtos.Message)) {
        return super.equals(obj);
      }
      br.quixada.ufc.si.classProto.MessageProtos.Message other = (br.quixada.ufc.si.classProto.MessageProtos.Message) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasObfReference() != other.hasObfReference()) return false;
      if (hasObfReference()) {
        if (!getObfReference()
            .equals(other.getObfReference())) return false;
      }
      if (hasMethodId() != other.hasMethodId()) return false;
      if (hasMethodId()) {
        if (!getMethodId()
            .equals(other.getMethodId())) return false;
      }
      if (hasArguments() != other.hasArguments()) return false;
      if (hasArguments()) {
        if (!getArguments()
            .equals(other.getArguments())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasObfReference()) {
        hash = (37 * hash) + OBFREFERENCE_FIELD_NUMBER;
        hash = (53 * hash) + getObfReference().hashCode();
      }
      if (hasMethodId()) {
        hash = (37 * hash) + METHODID_FIELD_NUMBER;
        hash = (53 * hash) + getMethodId().hashCode();
      }
      if (hasArguments()) {
        hash = (37 * hash) + ARGUMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getArguments().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.quixada.ufc.si.classProto.MessageProtos.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Message)
        br.quixada.ufc.si.classProto.MessageProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.quixada.ufc.si.classProto.MessageProtos.internal_static_tutorial_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.quixada.ufc.si.classProto.MessageProtos.internal_static_tutorial_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.quixada.ufc.si.classProto.MessageProtos.Message.class, br.quixada.ufc.si.classProto.MessageProtos.Message.Builder.class);
      }

      // Construct using br.quixada.ufc.si.classProto.MessageProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        obfReference_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        methodId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        arguments_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.quixada.ufc.si.classProto.MessageProtos.internal_static_tutorial_Message_descriptor;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.MessageProtos.Message getDefaultInstanceForType() {
        return br.quixada.ufc.si.classProto.MessageProtos.Message.getDefaultInstance();
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.MessageProtos.Message build() {
        br.quixada.ufc.si.classProto.MessageProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.MessageProtos.Message buildPartial() {
        br.quixada.ufc.si.classProto.MessageProtos.Message result = new br.quixada.ufc.si.classProto.MessageProtos.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.obfReference_ = obfReference_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.methodId_ = methodId_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.arguments_ = arguments_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.quixada.ufc.si.classProto.MessageProtos.Message) {
          return mergeFrom((br.quixada.ufc.si.classProto.MessageProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.quixada.ufc.si.classProto.MessageProtos.Message other) {
        if (other == br.quixada.ufc.si.classProto.MessageProtos.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasObfReference()) {
          bitField0_ |= 0x00000004;
          obfReference_ = other.obfReference_;
          onChanged();
        }
        if (other.hasMethodId()) {
          bitField0_ |= 0x00000008;
          methodId_ = other.methodId_;
          onChanged();
        }
        if (other.hasArguments()) {
          setArguments(other.getArguments());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.quixada.ufc.si.classProto.MessageProtos.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.quixada.ufc.si.classProto.MessageProtos.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>optional int32 type = 1;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object obfReference_ = "";
      /**
       * <code>optional string obfReference = 3;</code>
       * @return Whether the obfReference field is set.
       */
      public boolean hasObfReference() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string obfReference = 3;</code>
       * @return The obfReference.
       */
      public java.lang.String getObfReference() {
        java.lang.Object ref = obfReference_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            obfReference_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string obfReference = 3;</code>
       * @return The bytes for obfReference.
       */
      public com.google.protobuf.ByteString
          getObfReferenceBytes() {
        java.lang.Object ref = obfReference_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          obfReference_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string obfReference = 3;</code>
       * @param value The obfReference to set.
       * @return This builder for chaining.
       */
      public Builder setObfReference(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        obfReference_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string obfReference = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearObfReference() {
        bitField0_ = (bitField0_ & ~0x00000004);
        obfReference_ = getDefaultInstance().getObfReference();
        onChanged();
        return this;
      }
      /**
       * <code>optional string obfReference = 3;</code>
       * @param value The bytes for obfReference to set.
       * @return This builder for chaining.
       */
      public Builder setObfReferenceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        obfReference_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodId_ = "";
      /**
       * <code>optional string methodId = 4;</code>
       * @return Whether the methodId field is set.
       */
      public boolean hasMethodId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string methodId = 4;</code>
       * @return The methodId.
       */
      public java.lang.String getMethodId() {
        java.lang.Object ref = methodId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            methodId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string methodId = 4;</code>
       * @return The bytes for methodId.
       */
      public com.google.protobuf.ByteString
          getMethodIdBytes() {
        java.lang.Object ref = methodId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string methodId = 4;</code>
       * @param value The methodId to set.
       * @return This builder for chaining.
       */
      public Builder setMethodId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        methodId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        methodId_ = getDefaultInstance().getMethodId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodId = 4;</code>
       * @param value The bytes for methodId to set.
       * @return This builder for chaining.
       */
      public Builder setMethodIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        methodId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString arguments_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes arguments = 5;</code>
       * @return Whether the arguments field is set.
       */
      @java.lang.Override
      public boolean hasArguments() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bytes arguments = 5;</code>
       * @return The arguments.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getArguments() {
        return arguments_;
      }
      /**
       * <code>optional bytes arguments = 5;</code>
       * @param value The arguments to set.
       * @return This builder for chaining.
       */
      public Builder setArguments(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        arguments_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes arguments = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearArguments() {
        bitField0_ = (bitField0_ & ~0x00000010);
        arguments_ = getDefaultInstance().getArguments();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Message)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Message)
    private static final br.quixada.ufc.si.classProto.MessageProtos.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.quixada.ufc.si.classProto.MessageProtos.Message();
    }

    public static br.quixada.ufc.si.classProto.MessageProtos.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.quixada.ufc.si.classProto.MessageProtos.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.MessageBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tutorial.Message message = 1;</code>
     */
    java.util.List<br.quixada.ufc.si.classProto.MessageProtos.Message> 
        getMessageList();
    /**
     * <code>repeated .tutorial.Message message = 1;</code>
     */
    br.quixada.ufc.si.classProto.MessageProtos.Message getMessage(int index);
    /**
     * <code>repeated .tutorial.Message message = 1;</code>
     */
    int getMessageCount();
    /**
     * <code>repeated .tutorial.Message message = 1;</code>
     */
    java.util.List<? extends br.quixada.ufc.si.classProto.MessageProtos.MessageOrBuilder> 
        getMessageOrBuilderList();
    /**
     * <code>repeated .tutorial.Message message = 1;</code>
     */
    br.quixada.ufc.si.classProto.MessageProtos.MessageOrBuilder getMessageOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.MessageBook}
   */
  public static final class MessageBook extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.MessageBook)
      MessageBookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageBook.newBuilder() to construct.
    private MessageBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageBook() {
      message_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageBook();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                message_ = new java.util.ArrayList<br.quixada.ufc.si.classProto.MessageProtos.Message>();
                mutable_bitField0_ |= 0x00000001;
              }
              message_.add(
                  input.readMessage(br.quixada.ufc.si.classProto.MessageProtos.Message.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          message_ = java.util.Collections.unmodifiableList(message_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.quixada.ufc.si.classProto.MessageProtos.internal_static_tutorial_MessageBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.quixada.ufc.si.classProto.MessageProtos.internal_static_tutorial_MessageBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.quixada.ufc.si.classProto.MessageProtos.MessageBook.class, br.quixada.ufc.si.classProto.MessageProtos.MessageBook.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private java.util.List<br.quixada.ufc.si.classProto.MessageProtos.Message> message_;
    /**
     * <code>repeated .tutorial.Message message = 1;</code>
     */
    @java.lang.Override
    public java.util.List<br.quixada.ufc.si.classProto.MessageProtos.Message> getMessageList() {
      return message_;
    }
    /**
     * <code>repeated .tutorial.Message message = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends br.quixada.ufc.si.classProto.MessageProtos.MessageOrBuilder> 
        getMessageOrBuilderList() {
      return message_;
    }
    /**
     * <code>repeated .tutorial.Message message = 1;</code>
     */
    @java.lang.Override
    public int getMessageCount() {
      return message_.size();
    }
    /**
     * <code>repeated .tutorial.Message message = 1;</code>
     */
    @java.lang.Override
    public br.quixada.ufc.si.classProto.MessageProtos.Message getMessage(int index) {
      return message_.get(index);
    }
    /**
     * <code>repeated .tutorial.Message message = 1;</code>
     */
    @java.lang.Override
    public br.quixada.ufc.si.classProto.MessageProtos.MessageOrBuilder getMessageOrBuilder(
        int index) {
      return message_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < message_.size(); i++) {
        output.writeMessage(1, message_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < message_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, message_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.quixada.ufc.si.classProto.MessageProtos.MessageBook)) {
        return super.equals(obj);
      }
      br.quixada.ufc.si.classProto.MessageProtos.MessageBook other = (br.quixada.ufc.si.classProto.MessageProtos.MessageBook) obj;

      if (!getMessageList()
          .equals(other.getMessageList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessageCount() > 0) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.quixada.ufc.si.classProto.MessageProtos.MessageBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.MessageBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.MessageBook)
        br.quixada.ufc.si.classProto.MessageProtos.MessageBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.quixada.ufc.si.classProto.MessageProtos.internal_static_tutorial_MessageBook_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.quixada.ufc.si.classProto.MessageProtos.internal_static_tutorial_MessageBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.quixada.ufc.si.classProto.MessageProtos.MessageBook.class, br.quixada.ufc.si.classProto.MessageProtos.MessageBook.Builder.class);
      }

      // Construct using br.quixada.ufc.si.classProto.MessageProtos.MessageBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messageBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.quixada.ufc.si.classProto.MessageProtos.internal_static_tutorial_MessageBook_descriptor;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.MessageProtos.MessageBook getDefaultInstanceForType() {
        return br.quixada.ufc.si.classProto.MessageProtos.MessageBook.getDefaultInstance();
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.MessageProtos.MessageBook build() {
        br.quixada.ufc.si.classProto.MessageProtos.MessageBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.MessageProtos.MessageBook buildPartial() {
        br.quixada.ufc.si.classProto.MessageProtos.MessageBook result = new br.quixada.ufc.si.classProto.MessageProtos.MessageBook(this);
        int from_bitField0_ = bitField0_;
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            message_ = java.util.Collections.unmodifiableList(message_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.quixada.ufc.si.classProto.MessageProtos.MessageBook) {
          return mergeFrom((br.quixada.ufc.si.classProto.MessageProtos.MessageBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.quixada.ufc.si.classProto.MessageProtos.MessageBook other) {
        if (other == br.quixada.ufc.si.classProto.MessageProtos.MessageBook.getDefaultInstance()) return this;
        if (messageBuilder_ == null) {
          if (!other.message_.isEmpty()) {
            if (message_.isEmpty()) {
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessageIsMutable();
              message_.addAll(other.message_);
            }
            onChanged();
          }
        } else {
          if (!other.message_.isEmpty()) {
            if (messageBuilder_.isEmpty()) {
              messageBuilder_.dispose();
              messageBuilder_ = null;
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessageFieldBuilder() : null;
            } else {
              messageBuilder_.addAllMessages(other.message_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.quixada.ufc.si.classProto.MessageProtos.MessageBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.quixada.ufc.si.classProto.MessageProtos.MessageBook) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<br.quixada.ufc.si.classProto.MessageProtos.Message> message_ =
        java.util.Collections.emptyList();
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          message_ = new java.util.ArrayList<br.quixada.ufc.si.classProto.MessageProtos.Message>(message_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.quixada.ufc.si.classProto.MessageProtos.Message, br.quixada.ufc.si.classProto.MessageProtos.Message.Builder, br.quixada.ufc.si.classProto.MessageProtos.MessageOrBuilder> messageBuilder_;

      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public java.util.List<br.quixada.ufc.si.classProto.MessageProtos.Message> getMessageList() {
        if (messageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(message_);
        } else {
          return messageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public int getMessageCount() {
        if (messageBuilder_ == null) {
          return message_.size();
        } else {
          return messageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public br.quixada.ufc.si.classProto.MessageProtos.Message getMessage(int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);
        } else {
          return messageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public Builder setMessage(
          int index, br.quixada.ufc.si.classProto.MessageProtos.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.set(index, value);
          onChanged();
        } else {
          messageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public Builder setMessage(
          int index, br.quixada.ufc.si.classProto.MessageProtos.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public Builder addMessage(br.quixada.ufc.si.classProto.MessageProtos.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(value);
          onChanged();
        } else {
          messageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public Builder addMessage(
          int index, br.quixada.ufc.si.classProto.MessageProtos.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageIsMutable();
          message_.add(index, value);
          onChanged();
        } else {
          messageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public Builder addMessage(
          br.quixada.ufc.si.classProto.MessageProtos.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public Builder addMessage(
          int index, br.quixada.ufc.si.classProto.MessageProtos.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public Builder addAllMessage(
          java.lang.Iterable<? extends br.quixada.ufc.si.classProto.MessageProtos.Message> values) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, message_);
          onChanged();
        } else {
          messageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public Builder removeMessage(int index) {
        if (messageBuilder_ == null) {
          ensureMessageIsMutable();
          message_.remove(index);
          onChanged();
        } else {
          messageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public br.quixada.ufc.si.classProto.MessageProtos.Message.Builder getMessageBuilder(
          int index) {
        return getMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public br.quixada.ufc.si.classProto.MessageProtos.MessageOrBuilder getMessageOrBuilder(
          int index) {
        if (messageBuilder_ == null) {
          return message_.get(index);  } else {
          return messageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public java.util.List<? extends br.quixada.ufc.si.classProto.MessageProtos.MessageOrBuilder> 
           getMessageOrBuilderList() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(message_);
        }
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public br.quixada.ufc.si.classProto.MessageProtos.Message.Builder addMessageBuilder() {
        return getMessageFieldBuilder().addBuilder(
            br.quixada.ufc.si.classProto.MessageProtos.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public br.quixada.ufc.si.classProto.MessageProtos.Message.Builder addMessageBuilder(
          int index) {
        return getMessageFieldBuilder().addBuilder(
            index, br.quixada.ufc.si.classProto.MessageProtos.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Message message = 1;</code>
       */
      public java.util.List<br.quixada.ufc.si.classProto.MessageProtos.Message.Builder> 
           getMessageBuilderList() {
        return getMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.quixada.ufc.si.classProto.MessageProtos.Message, br.quixada.ufc.si.classProto.MessageProtos.Message.Builder, br.quixada.ufc.si.classProto.MessageProtos.MessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              br.quixada.ufc.si.classProto.MessageProtos.Message, br.quixada.ufc.si.classProto.MessageProtos.Message.Builder, br.quixada.ufc.si.classProto.MessageProtos.MessageOrBuilder>(
                  message_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.MessageBook)
    }

    // @@protoc_insertion_point(class_scope:tutorial.MessageBook)
    private static final br.quixada.ufc.si.classProto.MessageProtos.MessageBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.quixada.ufc.si.classProto.MessageProtos.MessageBook();
    }

    public static br.quixada.ufc.si.classProto.MessageProtos.MessageBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MessageBook>
        PARSER = new com.google.protobuf.AbstractParser<MessageBook>() {
      @java.lang.Override
      public MessageBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageBook(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageBook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageBook> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.quixada.ufc.si.classProto.MessageProtos.MessageBook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_MessageBook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_MessageBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/message.proto\022\010tutorial\"^\n\007Messa" +
      "ge\022\014\n\004type\030\001 \001(\005\022\n\n\002id\030\002 \001(\005\022\024\n\014obfRefer" +
      "ence\030\003 \001(\t\022\020\n\010methodId\030\004 \001(\t\022\021\n\targument" +
      "s\030\005 \001(\014\"1\n\013MessageBook\022\"\n\007message\030\001 \003(\0132" +
      "\021.tutorial.MessageB-\n\034br.quixada.ufc.si." +
      "classProtoB\rMessageProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Message_descriptor,
        new java.lang.String[] { "Type", "Id", "ObfReference", "MethodId", "Arguments", });
    internal_static_tutorial_MessageBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_MessageBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_MessageBook_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
