// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/quartoAlugado.proto

package br.quixada.ufc.si.classProto;

public final class QuartoAlugadoProtos {
  private QuartoAlugadoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuartoAlugadoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.QuartoAlugado)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return Whether the cpfHospede field is set.
     */
    boolean hasCpfHospede();
    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return The cpfHospede.
     */
    java.lang.String getCpfHospede();
    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return The bytes for cpfHospede.
     */
    com.google.protobuf.ByteString
        getCpfHospedeBytes();

    /**
     * <code>optional int32 numeroQuarto = 2;</code>
     * @return Whether the numeroQuarto field is set.
     */
    boolean hasNumeroQuarto();
    /**
     * <code>optional int32 numeroQuarto = 2;</code>
     * @return The numeroQuarto.
     */
    int getNumeroQuarto();

    /**
     * <code>optional string dataIni = 3;</code>
     * @return Whether the dataIni field is set.
     */
    boolean hasDataIni();
    /**
     * <code>optional string dataIni = 3;</code>
     * @return The dataIni.
     */
    java.lang.String getDataIni();
    /**
     * <code>optional string dataIni = 3;</code>
     * @return The bytes for dataIni.
     */
    com.google.protobuf.ByteString
        getDataIniBytes();

    /**
     * <code>optional string dataFim = 4;</code>
     * @return Whether the dataFim field is set.
     */
    boolean hasDataFim();
    /**
     * <code>optional string dataFim = 4;</code>
     * @return The dataFim.
     */
    java.lang.String getDataFim();
    /**
     * <code>optional string dataFim = 4;</code>
     * @return The bytes for dataFim.
     */
    com.google.protobuf.ByteString
        getDataFimBytes();
  }
  /**
   * Protobuf type {@code tutorial.QuartoAlugado}
   */
  public static final class QuartoAlugado extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.QuartoAlugado)
      QuartoAlugadoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuartoAlugado.newBuilder() to construct.
    private QuartoAlugado(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuartoAlugado() {
      cpfHospede_ = "";
      dataIni_ = "";
      dataFim_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QuartoAlugado();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuartoAlugado(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              cpfHospede_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              numeroQuarto_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              dataIni_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              dataFim_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.internal_static_tutorial_QuartoAlugado_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.internal_static_tutorial_QuartoAlugado_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.class, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder.class);
    }

    private int bitField0_;
    public static final int CPFHOSPEDE_FIELD_NUMBER = 1;
    private volatile java.lang.Object cpfHospede_;
    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return Whether the cpfHospede field is set.
     */
    @java.lang.Override
    public boolean hasCpfHospede() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return The cpfHospede.
     */
    @java.lang.Override
    public java.lang.String getCpfHospede() {
      java.lang.Object ref = cpfHospede_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cpfHospede_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return The bytes for cpfHospede.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCpfHospedeBytes() {
      java.lang.Object ref = cpfHospede_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpfHospede_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMEROQUARTO_FIELD_NUMBER = 2;
    private int numeroQuarto_;
    /**
     * <code>optional int32 numeroQuarto = 2;</code>
     * @return Whether the numeroQuarto field is set.
     */
    @java.lang.Override
    public boolean hasNumeroQuarto() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 numeroQuarto = 2;</code>
     * @return The numeroQuarto.
     */
    @java.lang.Override
    public int getNumeroQuarto() {
      return numeroQuarto_;
    }

    public static final int DATAINI_FIELD_NUMBER = 3;
    private volatile java.lang.Object dataIni_;
    /**
     * <code>optional string dataIni = 3;</code>
     * @return Whether the dataIni field is set.
     */
    @java.lang.Override
    public boolean hasDataIni() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string dataIni = 3;</code>
     * @return The dataIni.
     */
    @java.lang.Override
    public java.lang.String getDataIni() {
      java.lang.Object ref = dataIni_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataIni_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dataIni = 3;</code>
     * @return The bytes for dataIni.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataIniBytes() {
      java.lang.Object ref = dataIni_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataIni_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAFIM_FIELD_NUMBER = 4;
    private volatile java.lang.Object dataFim_;
    /**
     * <code>optional string dataFim = 4;</code>
     * @return Whether the dataFim field is set.
     */
    @java.lang.Override
    public boolean hasDataFim() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string dataFim = 4;</code>
     * @return The dataFim.
     */
    @java.lang.Override
    public java.lang.String getDataFim() {
      java.lang.Object ref = dataFim_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataFim_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dataFim = 4;</code>
     * @return The bytes for dataFim.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataFimBytes() {
      java.lang.Object ref = dataFim_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataFim_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cpfHospede_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, numeroQuarto_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataIni_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dataFim_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cpfHospede_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numeroQuarto_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataIni_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dataFim_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado)) {
        return super.equals(obj);
      }
      br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado other = (br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado) obj;

      if (hasCpfHospede() != other.hasCpfHospede()) return false;
      if (hasCpfHospede()) {
        if (!getCpfHospede()
            .equals(other.getCpfHospede())) return false;
      }
      if (hasNumeroQuarto() != other.hasNumeroQuarto()) return false;
      if (hasNumeroQuarto()) {
        if (getNumeroQuarto()
            != other.getNumeroQuarto()) return false;
      }
      if (hasDataIni() != other.hasDataIni()) return false;
      if (hasDataIni()) {
        if (!getDataIni()
            .equals(other.getDataIni())) return false;
      }
      if (hasDataFim() != other.hasDataFim()) return false;
      if (hasDataFim()) {
        if (!getDataFim()
            .equals(other.getDataFim())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCpfHospede()) {
        hash = (37 * hash) + CPFHOSPEDE_FIELD_NUMBER;
        hash = (53 * hash) + getCpfHospede().hashCode();
      }
      if (hasNumeroQuarto()) {
        hash = (37 * hash) + NUMEROQUARTO_FIELD_NUMBER;
        hash = (53 * hash) + getNumeroQuarto();
      }
      if (hasDataIni()) {
        hash = (37 * hash) + DATAINI_FIELD_NUMBER;
        hash = (53 * hash) + getDataIni().hashCode();
      }
      if (hasDataFim()) {
        hash = (37 * hash) + DATAFIM_FIELD_NUMBER;
        hash = (53 * hash) + getDataFim().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.QuartoAlugado}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.QuartoAlugado)
        br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.internal_static_tutorial_QuartoAlugado_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.internal_static_tutorial_QuartoAlugado_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.class, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder.class);
      }

      // Construct using br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cpfHospede_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        numeroQuarto_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        dataIni_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dataFim_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.internal_static_tutorial_QuartoAlugado_descriptor;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado getDefaultInstanceForType() {
        return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.getDefaultInstance();
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado build() {
        br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado buildPartial() {
        br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado result = new br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cpfHospede_ = cpfHospede_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.numeroQuarto_ = numeroQuarto_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataIni_ = dataIni_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dataFim_ = dataFim_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado) {
          return mergeFrom((br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado other) {
        if (other == br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.getDefaultInstance()) return this;
        if (other.hasCpfHospede()) {
          bitField0_ |= 0x00000001;
          cpfHospede_ = other.cpfHospede_;
          onChanged();
        }
        if (other.hasNumeroQuarto()) {
          setNumeroQuarto(other.getNumeroQuarto());
        }
        if (other.hasDataIni()) {
          bitField0_ |= 0x00000004;
          dataIni_ = other.dataIni_;
          onChanged();
        }
        if (other.hasDataFim()) {
          bitField0_ |= 0x00000008;
          dataFim_ = other.dataFim_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object cpfHospede_ = "";
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @return Whether the cpfHospede field is set.
       */
      public boolean hasCpfHospede() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @return The cpfHospede.
       */
      public java.lang.String getCpfHospede() {
        java.lang.Object ref = cpfHospede_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cpfHospede_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @return The bytes for cpfHospede.
       */
      public com.google.protobuf.ByteString
          getCpfHospedeBytes() {
        java.lang.Object ref = cpfHospede_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cpfHospede_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @param value The cpfHospede to set.
       * @return This builder for chaining.
       */
      public Builder setCpfHospede(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cpfHospede_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpfHospede() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cpfHospede_ = getDefaultInstance().getCpfHospede();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @param value The bytes for cpfHospede to set.
       * @return This builder for chaining.
       */
      public Builder setCpfHospedeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cpfHospede_ = value;
        onChanged();
        return this;
      }

      private int numeroQuarto_ ;
      /**
       * <code>optional int32 numeroQuarto = 2;</code>
       * @return Whether the numeroQuarto field is set.
       */
      @java.lang.Override
      public boolean hasNumeroQuarto() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 numeroQuarto = 2;</code>
       * @return The numeroQuarto.
       */
      @java.lang.Override
      public int getNumeroQuarto() {
        return numeroQuarto_;
      }
      /**
       * <code>optional int32 numeroQuarto = 2;</code>
       * @param value The numeroQuarto to set.
       * @return This builder for chaining.
       */
      public Builder setNumeroQuarto(int value) {
        bitField0_ |= 0x00000002;
        numeroQuarto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 numeroQuarto = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumeroQuarto() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numeroQuarto_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object dataIni_ = "";
      /**
       * <code>optional string dataIni = 3;</code>
       * @return Whether the dataIni field is set.
       */
      public boolean hasDataIni() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string dataIni = 3;</code>
       * @return The dataIni.
       */
      public java.lang.String getDataIni() {
        java.lang.Object ref = dataIni_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataIni_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dataIni = 3;</code>
       * @return The bytes for dataIni.
       */
      public com.google.protobuf.ByteString
          getDataIniBytes() {
        java.lang.Object ref = dataIni_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataIni_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dataIni = 3;</code>
       * @param value The dataIni to set.
       * @return This builder for chaining.
       */
      public Builder setDataIni(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataIni_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataIni = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataIni() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataIni_ = getDefaultInstance().getDataIni();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataIni = 3;</code>
       * @param value The bytes for dataIni to set.
       * @return This builder for chaining.
       */
      public Builder setDataIniBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataIni_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataFim_ = "";
      /**
       * <code>optional string dataFim = 4;</code>
       * @return Whether the dataFim field is set.
       */
      public boolean hasDataFim() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string dataFim = 4;</code>
       * @return The dataFim.
       */
      public java.lang.String getDataFim() {
        java.lang.Object ref = dataFim_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataFim_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dataFim = 4;</code>
       * @return The bytes for dataFim.
       */
      public com.google.protobuf.ByteString
          getDataFimBytes() {
        java.lang.Object ref = dataFim_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataFim_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dataFim = 4;</code>
       * @param value The dataFim to set.
       * @return This builder for chaining.
       */
      public Builder setDataFim(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dataFim_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataFim = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataFim() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dataFim_ = getDefaultInstance().getDataFim();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataFim = 4;</code>
       * @param value The bytes for dataFim to set.
       * @return This builder for chaining.
       */
      public Builder setDataFimBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dataFim_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.QuartoAlugado)
    }

    // @@protoc_insertion_point(class_scope:tutorial.QuartoAlugado)
    private static final br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado();
    }

    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<QuartoAlugado>
        PARSER = new com.google.protobuf.AbstractParser<QuartoAlugado>() {
      @java.lang.Override
      public QuartoAlugado parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuartoAlugado(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuartoAlugado> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuartoAlugado> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QuartoAlugadoBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.QuartoAlugadoBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
     */
    java.util.List<br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado> 
        getQuartoAlugadoList();
    /**
     * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
     */
    br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado getQuartoAlugado(int index);
    /**
     * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
     */
    int getQuartoAlugadoCount();
    /**
     * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
     */
    java.util.List<? extends br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoOrBuilder> 
        getQuartoAlugadoOrBuilderList();
    /**
     * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
     */
    br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoOrBuilder getQuartoAlugadoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.QuartoAlugadoBook}
   */
  public static final class QuartoAlugadoBook extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.QuartoAlugadoBook)
      QuartoAlugadoBookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuartoAlugadoBook.newBuilder() to construct.
    private QuartoAlugadoBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuartoAlugadoBook() {
      quartoAlugado_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QuartoAlugadoBook();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuartoAlugadoBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                quartoAlugado_ = new java.util.ArrayList<br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado>();
                mutable_bitField0_ |= 0x00000001;
              }
              quartoAlugado_.add(
                  input.readMessage(br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          quartoAlugado_ = java.util.Collections.unmodifiableList(quartoAlugado_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.internal_static_tutorial_QuartoAlugadoBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.internal_static_tutorial_QuartoAlugadoBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook.class, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook.Builder.class);
    }

    public static final int QUARTOALUGADO_FIELD_NUMBER = 1;
    private java.util.List<br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado> quartoAlugado_;
    /**
     * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
     */
    @java.lang.Override
    public java.util.List<br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado> getQuartoAlugadoList() {
      return quartoAlugado_;
    }
    /**
     * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoOrBuilder> 
        getQuartoAlugadoOrBuilderList() {
      return quartoAlugado_;
    }
    /**
     * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
     */
    @java.lang.Override
    public int getQuartoAlugadoCount() {
      return quartoAlugado_.size();
    }
    /**
     * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
     */
    @java.lang.Override
    public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado getQuartoAlugado(int index) {
      return quartoAlugado_.get(index);
    }
    /**
     * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
     */
    @java.lang.Override
    public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoOrBuilder getQuartoAlugadoOrBuilder(
        int index) {
      return quartoAlugado_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < quartoAlugado_.size(); i++) {
        output.writeMessage(1, quartoAlugado_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < quartoAlugado_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, quartoAlugado_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook)) {
        return super.equals(obj);
      }
      br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook other = (br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook) obj;

      if (!getQuartoAlugadoList()
          .equals(other.getQuartoAlugadoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getQuartoAlugadoCount() > 0) {
        hash = (37 * hash) + QUARTOALUGADO_FIELD_NUMBER;
        hash = (53 * hash) + getQuartoAlugadoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.QuartoAlugadoBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.QuartoAlugadoBook)
        br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.internal_static_tutorial_QuartoAlugadoBook_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.internal_static_tutorial_QuartoAlugadoBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook.class, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook.Builder.class);
      }

      // Construct using br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getQuartoAlugadoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (quartoAlugadoBuilder_ == null) {
          quartoAlugado_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          quartoAlugadoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.internal_static_tutorial_QuartoAlugadoBook_descriptor;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook getDefaultInstanceForType() {
        return br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook.getDefaultInstance();
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook build() {
        br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook buildPartial() {
        br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook result = new br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook(this);
        int from_bitField0_ = bitField0_;
        if (quartoAlugadoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            quartoAlugado_ = java.util.Collections.unmodifiableList(quartoAlugado_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.quartoAlugado_ = quartoAlugado_;
        } else {
          result.quartoAlugado_ = quartoAlugadoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook) {
          return mergeFrom((br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook other) {
        if (other == br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook.getDefaultInstance()) return this;
        if (quartoAlugadoBuilder_ == null) {
          if (!other.quartoAlugado_.isEmpty()) {
            if (quartoAlugado_.isEmpty()) {
              quartoAlugado_ = other.quartoAlugado_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureQuartoAlugadoIsMutable();
              quartoAlugado_.addAll(other.quartoAlugado_);
            }
            onChanged();
          }
        } else {
          if (!other.quartoAlugado_.isEmpty()) {
            if (quartoAlugadoBuilder_.isEmpty()) {
              quartoAlugadoBuilder_.dispose();
              quartoAlugadoBuilder_ = null;
              quartoAlugado_ = other.quartoAlugado_;
              bitField0_ = (bitField0_ & ~0x00000001);
              quartoAlugadoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getQuartoAlugadoFieldBuilder() : null;
            } else {
              quartoAlugadoBuilder_.addAllMessages(other.quartoAlugado_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado> quartoAlugado_ =
        java.util.Collections.emptyList();
      private void ensureQuartoAlugadoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          quartoAlugado_ = new java.util.ArrayList<br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado>(quartoAlugado_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoOrBuilder> quartoAlugadoBuilder_;

      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public java.util.List<br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado> getQuartoAlugadoList() {
        if (quartoAlugadoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(quartoAlugado_);
        } else {
          return quartoAlugadoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public int getQuartoAlugadoCount() {
        if (quartoAlugadoBuilder_ == null) {
          return quartoAlugado_.size();
        } else {
          return quartoAlugadoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado getQuartoAlugado(int index) {
        if (quartoAlugadoBuilder_ == null) {
          return quartoAlugado_.get(index);
        } else {
          return quartoAlugadoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public Builder setQuartoAlugado(
          int index, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado value) {
        if (quartoAlugadoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuartoAlugadoIsMutable();
          quartoAlugado_.set(index, value);
          onChanged();
        } else {
          quartoAlugadoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public Builder setQuartoAlugado(
          int index, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder builderForValue) {
        if (quartoAlugadoBuilder_ == null) {
          ensureQuartoAlugadoIsMutable();
          quartoAlugado_.set(index, builderForValue.build());
          onChanged();
        } else {
          quartoAlugadoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public Builder addQuartoAlugado(br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado value) {
        if (quartoAlugadoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuartoAlugadoIsMutable();
          quartoAlugado_.add(value);
          onChanged();
        } else {
          quartoAlugadoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public Builder addQuartoAlugado(
          int index, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado value) {
        if (quartoAlugadoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuartoAlugadoIsMutable();
          quartoAlugado_.add(index, value);
          onChanged();
        } else {
          quartoAlugadoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public Builder addQuartoAlugado(
          br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder builderForValue) {
        if (quartoAlugadoBuilder_ == null) {
          ensureQuartoAlugadoIsMutable();
          quartoAlugado_.add(builderForValue.build());
          onChanged();
        } else {
          quartoAlugadoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public Builder addQuartoAlugado(
          int index, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder builderForValue) {
        if (quartoAlugadoBuilder_ == null) {
          ensureQuartoAlugadoIsMutable();
          quartoAlugado_.add(index, builderForValue.build());
          onChanged();
        } else {
          quartoAlugadoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public Builder addAllQuartoAlugado(
          java.lang.Iterable<? extends br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado> values) {
        if (quartoAlugadoBuilder_ == null) {
          ensureQuartoAlugadoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, quartoAlugado_);
          onChanged();
        } else {
          quartoAlugadoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public Builder clearQuartoAlugado() {
        if (quartoAlugadoBuilder_ == null) {
          quartoAlugado_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          quartoAlugadoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public Builder removeQuartoAlugado(int index) {
        if (quartoAlugadoBuilder_ == null) {
          ensureQuartoAlugadoIsMutable();
          quartoAlugado_.remove(index);
          onChanged();
        } else {
          quartoAlugadoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder getQuartoAlugadoBuilder(
          int index) {
        return getQuartoAlugadoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoOrBuilder getQuartoAlugadoOrBuilder(
          int index) {
        if (quartoAlugadoBuilder_ == null) {
          return quartoAlugado_.get(index);  } else {
          return quartoAlugadoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public java.util.List<? extends br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoOrBuilder> 
           getQuartoAlugadoOrBuilderList() {
        if (quartoAlugadoBuilder_ != null) {
          return quartoAlugadoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(quartoAlugado_);
        }
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder addQuartoAlugadoBuilder() {
        return getQuartoAlugadoFieldBuilder().addBuilder(
            br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder addQuartoAlugadoBuilder(
          int index) {
        return getQuartoAlugadoFieldBuilder().addBuilder(
            index, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.QuartoAlugado quartoAlugado = 1;</code>
       */
      public java.util.List<br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder> 
           getQuartoAlugadoBuilderList() {
        return getQuartoAlugadoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoOrBuilder> 
          getQuartoAlugadoFieldBuilder() {
        if (quartoAlugadoBuilder_ == null) {
          quartoAlugadoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugado.Builder, br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoOrBuilder>(
                  quartoAlugado_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          quartoAlugado_ = null;
        }
        return quartoAlugadoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.QuartoAlugadoBook)
    }

    // @@protoc_insertion_point(class_scope:tutorial.QuartoAlugadoBook)
    private static final br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook();
    }

    public static br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<QuartoAlugadoBook>
        PARSER = new com.google.protobuf.AbstractParser<QuartoAlugadoBook>() {
      @java.lang.Override
      public QuartoAlugadoBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuartoAlugadoBook(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuartoAlugadoBook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuartoAlugadoBook> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.quixada.ufc.si.classProto.QuartoAlugadoProtos.QuartoAlugadoBook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_QuartoAlugado_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_QuartoAlugado_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_QuartoAlugadoBook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_QuartoAlugadoBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/quartoAlugado.proto\022\010tutorial\"[\n" +
      "\rQuartoAlugado\022\022\n\ncpfHospede\030\001 \001(\t\022\024\n\014nu" +
      "meroQuarto\030\002 \001(\005\022\017\n\007dataIni\030\003 \001(\t\022\017\n\007dat" +
      "aFim\030\004 \001(\t\"C\n\021QuartoAlugadoBook\022.\n\rquart" +
      "oAlugado\030\001 \003(\0132\027.tutorial.QuartoAlugadoB" +
      "3\n\034br.quixada.ufc.si.classProtoB\023QuartoA" +
      "lugadoProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_QuartoAlugado_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_QuartoAlugado_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_QuartoAlugado_descriptor,
        new java.lang.String[] { "CpfHospede", "NumeroQuarto", "DataIni", "DataFim", });
    internal_static_tutorial_QuartoAlugadoBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_QuartoAlugadoBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_QuartoAlugadoBook_descriptor,
        new java.lang.String[] { "QuartoAlugado", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
