// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/quarto.proto

package br.quixada.ufc.si.classProto;

public final class QuartoProtos {
  private QuartoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuartoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Quarto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 numero = 1;</code>
     * @return Whether the numero field is set.
     */
    boolean hasNumero();
    /**
     * <code>optional int32 numero = 1;</code>
     * @return The numero.
     */
    int getNumero();

    /**
     * <code>optional double valorDiaria = 2;</code>
     * @return Whether the valorDiaria field is set.
     */
    boolean hasValorDiaria();
    /**
     * <code>optional double valorDiaria = 2;</code>
     * @return The valorDiaria.
     */
    double getValorDiaria();

    /**
     * <code>optional string descricao = 3;</code>
     * @return Whether the descricao field is set.
     */
    boolean hasDescricao();
    /**
     * <code>optional string descricao = 3;</code>
     * @return The descricao.
     */
    java.lang.String getDescricao();
    /**
     * <code>optional string descricao = 3;</code>
     * @return The bytes for descricao.
     */
    com.google.protobuf.ByteString
        getDescricaoBytes();

    /**
     * <code>optional bool disponivel = 4;</code>
     * @return Whether the disponivel field is set.
     */
    boolean hasDisponivel();
    /**
     * <code>optional bool disponivel = 4;</code>
     * @return The disponivel.
     */
    boolean getDisponivel();
  }
  /**
   * Protobuf type {@code tutorial.Quarto}
   */
  public static final class Quarto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Quarto)
      QuartoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Quarto.newBuilder() to construct.
    private Quarto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Quarto() {
      descricao_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Quarto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Quarto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              numero_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              valorDiaria_ = input.readDouble();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              descricao_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              disponivel_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.quixada.ufc.si.classProto.QuartoProtos.internal_static_tutorial_Quarto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.quixada.ufc.si.classProto.QuartoProtos.internal_static_tutorial_Quarto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.quixada.ufc.si.classProto.QuartoProtos.Quarto.class, br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder.class);
    }

    private int bitField0_;
    public static final int NUMERO_FIELD_NUMBER = 1;
    private int numero_;
    /**
     * <code>optional int32 numero = 1;</code>
     * @return Whether the numero field is set.
     */
    @java.lang.Override
    public boolean hasNumero() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 numero = 1;</code>
     * @return The numero.
     */
    @java.lang.Override
    public int getNumero() {
      return numero_;
    }

    public static final int VALORDIARIA_FIELD_NUMBER = 2;
    private double valorDiaria_;
    /**
     * <code>optional double valorDiaria = 2;</code>
     * @return Whether the valorDiaria field is set.
     */
    @java.lang.Override
    public boolean hasValorDiaria() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional double valorDiaria = 2;</code>
     * @return The valorDiaria.
     */
    @java.lang.Override
    public double getValorDiaria() {
      return valorDiaria_;
    }

    public static final int DESCRICAO_FIELD_NUMBER = 3;
    private volatile java.lang.Object descricao_;
    /**
     * <code>optional string descricao = 3;</code>
     * @return Whether the descricao field is set.
     */
    @java.lang.Override
    public boolean hasDescricao() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string descricao = 3;</code>
     * @return The descricao.
     */
    @java.lang.Override
    public java.lang.String getDescricao() {
      java.lang.Object ref = descricao_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          descricao_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string descricao = 3;</code>
     * @return The bytes for descricao.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescricaoBytes() {
      java.lang.Object ref = descricao_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descricao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISPONIVEL_FIELD_NUMBER = 4;
    private boolean disponivel_;
    /**
     * <code>optional bool disponivel = 4;</code>
     * @return Whether the disponivel field is set.
     */
    @java.lang.Override
    public boolean hasDisponivel() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool disponivel = 4;</code>
     * @return The disponivel.
     */
    @java.lang.Override
    public boolean getDisponivel() {
      return disponivel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, numero_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, valorDiaria_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, descricao_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, disponivel_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, numero_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, valorDiaria_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, descricao_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, disponivel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.quixada.ufc.si.classProto.QuartoProtos.Quarto)) {
        return super.equals(obj);
      }
      br.quixada.ufc.si.classProto.QuartoProtos.Quarto other = (br.quixada.ufc.si.classProto.QuartoProtos.Quarto) obj;

      if (hasNumero() != other.hasNumero()) return false;
      if (hasNumero()) {
        if (getNumero()
            != other.getNumero()) return false;
      }
      if (hasValorDiaria() != other.hasValorDiaria()) return false;
      if (hasValorDiaria()) {
        if (java.lang.Double.doubleToLongBits(getValorDiaria())
            != java.lang.Double.doubleToLongBits(
                other.getValorDiaria())) return false;
      }
      if (hasDescricao() != other.hasDescricao()) return false;
      if (hasDescricao()) {
        if (!getDescricao()
            .equals(other.getDescricao())) return false;
      }
      if (hasDisponivel() != other.hasDisponivel()) return false;
      if (hasDisponivel()) {
        if (getDisponivel()
            != other.getDisponivel()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNumero()) {
        hash = (37 * hash) + NUMERO_FIELD_NUMBER;
        hash = (53 * hash) + getNumero();
      }
      if (hasValorDiaria()) {
        hash = (37 * hash) + VALORDIARIA_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getValorDiaria()));
      }
      if (hasDescricao()) {
        hash = (37 * hash) + DESCRICAO_FIELD_NUMBER;
        hash = (53 * hash) + getDescricao().hashCode();
      }
      if (hasDisponivel()) {
        hash = (37 * hash) + DISPONIVEL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDisponivel());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.quixada.ufc.si.classProto.QuartoProtos.Quarto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Quarto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Quarto)
        br.quixada.ufc.si.classProto.QuartoProtos.QuartoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.quixada.ufc.si.classProto.QuartoProtos.internal_static_tutorial_Quarto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.quixada.ufc.si.classProto.QuartoProtos.internal_static_tutorial_Quarto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.quixada.ufc.si.classProto.QuartoProtos.Quarto.class, br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder.class);
      }

      // Construct using br.quixada.ufc.si.classProto.QuartoProtos.Quarto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numero_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        valorDiaria_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        descricao_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        disponivel_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.quixada.ufc.si.classProto.QuartoProtos.internal_static_tutorial_Quarto_descriptor;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoProtos.Quarto getDefaultInstanceForType() {
        return br.quixada.ufc.si.classProto.QuartoProtos.Quarto.getDefaultInstance();
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoProtos.Quarto build() {
        br.quixada.ufc.si.classProto.QuartoProtos.Quarto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoProtos.Quarto buildPartial() {
        br.quixada.ufc.si.classProto.QuartoProtos.Quarto result = new br.quixada.ufc.si.classProto.QuartoProtos.Quarto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.numero_ = numero_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.valorDiaria_ = valorDiaria_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.descricao_ = descricao_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.disponivel_ = disponivel_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.quixada.ufc.si.classProto.QuartoProtos.Quarto) {
          return mergeFrom((br.quixada.ufc.si.classProto.QuartoProtos.Quarto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.quixada.ufc.si.classProto.QuartoProtos.Quarto other) {
        if (other == br.quixada.ufc.si.classProto.QuartoProtos.Quarto.getDefaultInstance()) return this;
        if (other.hasNumero()) {
          setNumero(other.getNumero());
        }
        if (other.hasValorDiaria()) {
          setValorDiaria(other.getValorDiaria());
        }
        if (other.hasDescricao()) {
          bitField0_ |= 0x00000004;
          descricao_ = other.descricao_;
          onChanged();
        }
        if (other.hasDisponivel()) {
          setDisponivel(other.getDisponivel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.quixada.ufc.si.classProto.QuartoProtos.Quarto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.quixada.ufc.si.classProto.QuartoProtos.Quarto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int numero_ ;
      /**
       * <code>optional int32 numero = 1;</code>
       * @return Whether the numero field is set.
       */
      @java.lang.Override
      public boolean hasNumero() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 numero = 1;</code>
       * @return The numero.
       */
      @java.lang.Override
      public int getNumero() {
        return numero_;
      }
      /**
       * <code>optional int32 numero = 1;</code>
       * @param value The numero to set.
       * @return This builder for chaining.
       */
      public Builder setNumero(int value) {
        bitField0_ |= 0x00000001;
        numero_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 numero = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumero() {
        bitField0_ = (bitField0_ & ~0x00000001);
        numero_ = 0;
        onChanged();
        return this;
      }

      private double valorDiaria_ ;
      /**
       * <code>optional double valorDiaria = 2;</code>
       * @return Whether the valorDiaria field is set.
       */
      @java.lang.Override
      public boolean hasValorDiaria() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional double valorDiaria = 2;</code>
       * @return The valorDiaria.
       */
      @java.lang.Override
      public double getValorDiaria() {
        return valorDiaria_;
      }
      /**
       * <code>optional double valorDiaria = 2;</code>
       * @param value The valorDiaria to set.
       * @return This builder for chaining.
       */
      public Builder setValorDiaria(double value) {
        bitField0_ |= 0x00000002;
        valorDiaria_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double valorDiaria = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValorDiaria() {
        bitField0_ = (bitField0_ & ~0x00000002);
        valorDiaria_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object descricao_ = "";
      /**
       * <code>optional string descricao = 3;</code>
       * @return Whether the descricao field is set.
       */
      public boolean hasDescricao() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string descricao = 3;</code>
       * @return The descricao.
       */
      public java.lang.String getDescricao() {
        java.lang.Object ref = descricao_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            descricao_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string descricao = 3;</code>
       * @return The bytes for descricao.
       */
      public com.google.protobuf.ByteString
          getDescricaoBytes() {
        java.lang.Object ref = descricao_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          descricao_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string descricao = 3;</code>
       * @param value The descricao to set.
       * @return This builder for chaining.
       */
      public Builder setDescricao(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        descricao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string descricao = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescricao() {
        bitField0_ = (bitField0_ & ~0x00000004);
        descricao_ = getDefaultInstance().getDescricao();
        onChanged();
        return this;
      }
      /**
       * <code>optional string descricao = 3;</code>
       * @param value The bytes for descricao to set.
       * @return This builder for chaining.
       */
      public Builder setDescricaoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        descricao_ = value;
        onChanged();
        return this;
      }

      private boolean disponivel_ ;
      /**
       * <code>optional bool disponivel = 4;</code>
       * @return Whether the disponivel field is set.
       */
      @java.lang.Override
      public boolean hasDisponivel() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bool disponivel = 4;</code>
       * @return The disponivel.
       */
      @java.lang.Override
      public boolean getDisponivel() {
        return disponivel_;
      }
      /**
       * <code>optional bool disponivel = 4;</code>
       * @param value The disponivel to set.
       * @return This builder for chaining.
       */
      public Builder setDisponivel(boolean value) {
        bitField0_ |= 0x00000008;
        disponivel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool disponivel = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDisponivel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        disponivel_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Quarto)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Quarto)
    private static final br.quixada.ufc.si.classProto.QuartoProtos.Quarto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.quixada.ufc.si.classProto.QuartoProtos.Quarto();
    }

    public static br.quixada.ufc.si.classProto.QuartoProtos.Quarto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Quarto>
        PARSER = new com.google.protobuf.AbstractParser<Quarto>() {
      @java.lang.Override
      public Quarto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Quarto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Quarto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Quarto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.quixada.ufc.si.classProto.QuartoProtos.Quarto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QuartoBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.QuartoBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tutorial.Quarto quarto = 1;</code>
     */
    java.util.List<br.quixada.ufc.si.classProto.QuartoProtos.Quarto> 
        getQuartoList();
    /**
     * <code>repeated .tutorial.Quarto quarto = 1;</code>
     */
    br.quixada.ufc.si.classProto.QuartoProtos.Quarto getQuarto(int index);
    /**
     * <code>repeated .tutorial.Quarto quarto = 1;</code>
     */
    int getQuartoCount();
    /**
     * <code>repeated .tutorial.Quarto quarto = 1;</code>
     */
    java.util.List<? extends br.quixada.ufc.si.classProto.QuartoProtos.QuartoOrBuilder> 
        getQuartoOrBuilderList();
    /**
     * <code>repeated .tutorial.Quarto quarto = 1;</code>
     */
    br.quixada.ufc.si.classProto.QuartoProtos.QuartoOrBuilder getQuartoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.QuartoBook}
   */
  public static final class QuartoBook extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.QuartoBook)
      QuartoBookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuartoBook.newBuilder() to construct.
    private QuartoBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuartoBook() {
      quarto_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QuartoBook();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuartoBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                quarto_ = new java.util.ArrayList<br.quixada.ufc.si.classProto.QuartoProtos.Quarto>();
                mutable_bitField0_ |= 0x00000001;
              }
              quarto_.add(
                  input.readMessage(br.quixada.ufc.si.classProto.QuartoProtos.Quarto.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          quarto_ = java.util.Collections.unmodifiableList(quarto_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.quixada.ufc.si.classProto.QuartoProtos.internal_static_tutorial_QuartoBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.quixada.ufc.si.classProto.QuartoProtos.internal_static_tutorial_QuartoBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook.class, br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook.Builder.class);
    }

    public static final int QUARTO_FIELD_NUMBER = 1;
    private java.util.List<br.quixada.ufc.si.classProto.QuartoProtos.Quarto> quarto_;
    /**
     * <code>repeated .tutorial.Quarto quarto = 1;</code>
     */
    @java.lang.Override
    public java.util.List<br.quixada.ufc.si.classProto.QuartoProtos.Quarto> getQuartoList() {
      return quarto_;
    }
    /**
     * <code>repeated .tutorial.Quarto quarto = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends br.quixada.ufc.si.classProto.QuartoProtos.QuartoOrBuilder> 
        getQuartoOrBuilderList() {
      return quarto_;
    }
    /**
     * <code>repeated .tutorial.Quarto quarto = 1;</code>
     */
    @java.lang.Override
    public int getQuartoCount() {
      return quarto_.size();
    }
    /**
     * <code>repeated .tutorial.Quarto quarto = 1;</code>
     */
    @java.lang.Override
    public br.quixada.ufc.si.classProto.QuartoProtos.Quarto getQuarto(int index) {
      return quarto_.get(index);
    }
    /**
     * <code>repeated .tutorial.Quarto quarto = 1;</code>
     */
    @java.lang.Override
    public br.quixada.ufc.si.classProto.QuartoProtos.QuartoOrBuilder getQuartoOrBuilder(
        int index) {
      return quarto_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < quarto_.size(); i++) {
        output.writeMessage(1, quarto_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < quarto_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, quarto_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook)) {
        return super.equals(obj);
      }
      br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook other = (br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook) obj;

      if (!getQuartoList()
          .equals(other.getQuartoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getQuartoCount() > 0) {
        hash = (37 * hash) + QUARTO_FIELD_NUMBER;
        hash = (53 * hash) + getQuartoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.QuartoBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.QuartoBook)
        br.quixada.ufc.si.classProto.QuartoProtos.QuartoBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.quixada.ufc.si.classProto.QuartoProtos.internal_static_tutorial_QuartoBook_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.quixada.ufc.si.classProto.QuartoProtos.internal_static_tutorial_QuartoBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook.class, br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook.Builder.class);
      }

      // Construct using br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getQuartoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (quartoBuilder_ == null) {
          quarto_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          quartoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.quixada.ufc.si.classProto.QuartoProtos.internal_static_tutorial_QuartoBook_descriptor;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook getDefaultInstanceForType() {
        return br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook.getDefaultInstance();
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook build() {
        br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook buildPartial() {
        br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook result = new br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook(this);
        int from_bitField0_ = bitField0_;
        if (quartoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            quarto_ = java.util.Collections.unmodifiableList(quarto_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.quarto_ = quarto_;
        } else {
          result.quarto_ = quartoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook) {
          return mergeFrom((br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook other) {
        if (other == br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook.getDefaultInstance()) return this;
        if (quartoBuilder_ == null) {
          if (!other.quarto_.isEmpty()) {
            if (quarto_.isEmpty()) {
              quarto_ = other.quarto_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureQuartoIsMutable();
              quarto_.addAll(other.quarto_);
            }
            onChanged();
          }
        } else {
          if (!other.quarto_.isEmpty()) {
            if (quartoBuilder_.isEmpty()) {
              quartoBuilder_.dispose();
              quartoBuilder_ = null;
              quarto_ = other.quarto_;
              bitField0_ = (bitField0_ & ~0x00000001);
              quartoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getQuartoFieldBuilder() : null;
            } else {
              quartoBuilder_.addAllMessages(other.quarto_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<br.quixada.ufc.si.classProto.QuartoProtos.Quarto> quarto_ =
        java.util.Collections.emptyList();
      private void ensureQuartoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          quarto_ = new java.util.ArrayList<br.quixada.ufc.si.classProto.QuartoProtos.Quarto>(quarto_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.quixada.ufc.si.classProto.QuartoProtos.Quarto, br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder, br.quixada.ufc.si.classProto.QuartoProtos.QuartoOrBuilder> quartoBuilder_;

      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public java.util.List<br.quixada.ufc.si.classProto.QuartoProtos.Quarto> getQuartoList() {
        if (quartoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(quarto_);
        } else {
          return quartoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public int getQuartoCount() {
        if (quartoBuilder_ == null) {
          return quarto_.size();
        } else {
          return quartoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public br.quixada.ufc.si.classProto.QuartoProtos.Quarto getQuarto(int index) {
        if (quartoBuilder_ == null) {
          return quarto_.get(index);
        } else {
          return quartoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public Builder setQuarto(
          int index, br.quixada.ufc.si.classProto.QuartoProtos.Quarto value) {
        if (quartoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuartoIsMutable();
          quarto_.set(index, value);
          onChanged();
        } else {
          quartoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public Builder setQuarto(
          int index, br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder builderForValue) {
        if (quartoBuilder_ == null) {
          ensureQuartoIsMutable();
          quarto_.set(index, builderForValue.build());
          onChanged();
        } else {
          quartoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public Builder addQuarto(br.quixada.ufc.si.classProto.QuartoProtos.Quarto value) {
        if (quartoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuartoIsMutable();
          quarto_.add(value);
          onChanged();
        } else {
          quartoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public Builder addQuarto(
          int index, br.quixada.ufc.si.classProto.QuartoProtos.Quarto value) {
        if (quartoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuartoIsMutable();
          quarto_.add(index, value);
          onChanged();
        } else {
          quartoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public Builder addQuarto(
          br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder builderForValue) {
        if (quartoBuilder_ == null) {
          ensureQuartoIsMutable();
          quarto_.add(builderForValue.build());
          onChanged();
        } else {
          quartoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public Builder addQuarto(
          int index, br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder builderForValue) {
        if (quartoBuilder_ == null) {
          ensureQuartoIsMutable();
          quarto_.add(index, builderForValue.build());
          onChanged();
        } else {
          quartoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public Builder addAllQuarto(
          java.lang.Iterable<? extends br.quixada.ufc.si.classProto.QuartoProtos.Quarto> values) {
        if (quartoBuilder_ == null) {
          ensureQuartoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, quarto_);
          onChanged();
        } else {
          quartoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public Builder clearQuarto() {
        if (quartoBuilder_ == null) {
          quarto_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          quartoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public Builder removeQuarto(int index) {
        if (quartoBuilder_ == null) {
          ensureQuartoIsMutable();
          quarto_.remove(index);
          onChanged();
        } else {
          quartoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder getQuartoBuilder(
          int index) {
        return getQuartoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public br.quixada.ufc.si.classProto.QuartoProtos.QuartoOrBuilder getQuartoOrBuilder(
          int index) {
        if (quartoBuilder_ == null) {
          return quarto_.get(index);  } else {
          return quartoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public java.util.List<? extends br.quixada.ufc.si.classProto.QuartoProtos.QuartoOrBuilder> 
           getQuartoOrBuilderList() {
        if (quartoBuilder_ != null) {
          return quartoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(quarto_);
        }
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder addQuartoBuilder() {
        return getQuartoFieldBuilder().addBuilder(
            br.quixada.ufc.si.classProto.QuartoProtos.Quarto.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder addQuartoBuilder(
          int index) {
        return getQuartoFieldBuilder().addBuilder(
            index, br.quixada.ufc.si.classProto.QuartoProtos.Quarto.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Quarto quarto = 1;</code>
       */
      public java.util.List<br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder> 
           getQuartoBuilderList() {
        return getQuartoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.quixada.ufc.si.classProto.QuartoProtos.Quarto, br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder, br.quixada.ufc.si.classProto.QuartoProtos.QuartoOrBuilder> 
          getQuartoFieldBuilder() {
        if (quartoBuilder_ == null) {
          quartoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              br.quixada.ufc.si.classProto.QuartoProtos.Quarto, br.quixada.ufc.si.classProto.QuartoProtos.Quarto.Builder, br.quixada.ufc.si.classProto.QuartoProtos.QuartoOrBuilder>(
                  quarto_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          quarto_ = null;
        }
        return quartoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.QuartoBook)
    }

    // @@protoc_insertion_point(class_scope:tutorial.QuartoBook)
    private static final br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook();
    }

    public static br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<QuartoBook>
        PARSER = new com.google.protobuf.AbstractParser<QuartoBook>() {
      @java.lang.Override
      public QuartoBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QuartoBook(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuartoBook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuartoBook> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.quixada.ufc.si.classProto.QuartoProtos.QuartoBook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Quarto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Quarto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_QuartoBook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_QuartoBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/quarto.proto\022\010tutorial\"T\n\006Quarto" +
      "\022\016\n\006numero\030\001 \001(\005\022\023\n\013valorDiaria\030\002 \001(\001\022\021\n" +
      "\tdescricao\030\003 \001(\t\022\022\n\ndisponivel\030\004 \001(\010\".\n\n" +
      "QuartoBook\022 \n\006quarto\030\001 \003(\0132\020.tutorial.Qu" +
      "artoB,\n\034br.quixada.ufc.si.classProtoB\014Qu" +
      "artoProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Quarto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Quarto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Quarto_descriptor,
        new java.lang.String[] { "Numero", "ValorDiaria", "Descricao", "Disponivel", });
    internal_static_tutorial_QuartoBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_QuartoBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_QuartoBook_descriptor,
        new java.lang.String[] { "Quarto", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
