// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/reserva.proto

package br.quixada.ufc.si.classProto;

public final class ReservaProtos {
  private ReservaProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReservaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Reserva)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return Whether the cpfHospede field is set.
     */
    boolean hasCpfHospede();
    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return The cpfHospede.
     */
    java.lang.String getCpfHospede();
    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return The bytes for cpfHospede.
     */
    com.google.protobuf.ByteString
        getCpfHospedeBytes();

    /**
     * <code>optional int32 numeroQuarto = 2;</code>
     * @return Whether the numeroQuarto field is set.
     */
    boolean hasNumeroQuarto();
    /**
     * <code>optional int32 numeroQuarto = 2;</code>
     * @return The numeroQuarto.
     */
    int getNumeroQuarto();

    /**
     * <code>optional string dataIni = 3;</code>
     * @return Whether the dataIni field is set.
     */
    boolean hasDataIni();
    /**
     * <code>optional string dataIni = 3;</code>
     * @return The dataIni.
     */
    java.lang.String getDataIni();
    /**
     * <code>optional string dataIni = 3;</code>
     * @return The bytes for dataIni.
     */
    com.google.protobuf.ByteString
        getDataIniBytes();

    /**
     * <code>optional string dataFim = 4;</code>
     * @return Whether the dataFim field is set.
     */
    boolean hasDataFim();
    /**
     * <code>optional string dataFim = 4;</code>
     * @return The dataFim.
     */
    java.lang.String getDataFim();
    /**
     * <code>optional string dataFim = 4;</code>
     * @return The bytes for dataFim.
     */
    com.google.protobuf.ByteString
        getDataFimBytes();
  }
  /**
   * Protobuf type {@code tutorial.Reserva}
   */
  public static final class Reserva extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Reserva)
      ReservaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Reserva.newBuilder() to construct.
    private Reserva(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Reserva() {
      cpfHospede_ = "";
      dataIni_ = "";
      dataFim_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Reserva();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Reserva(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              cpfHospede_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              numeroQuarto_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              dataIni_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              dataFim_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.quixada.ufc.si.classProto.ReservaProtos.internal_static_tutorial_Reserva_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.quixada.ufc.si.classProto.ReservaProtos.internal_static_tutorial_Reserva_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.quixada.ufc.si.classProto.ReservaProtos.Reserva.class, br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder.class);
    }

    private int bitField0_;
    public static final int CPFHOSPEDE_FIELD_NUMBER = 1;
    private volatile java.lang.Object cpfHospede_;
    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return Whether the cpfHospede field is set.
     */
    @java.lang.Override
    public boolean hasCpfHospede() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return The cpfHospede.
     */
    @java.lang.Override
    public java.lang.String getCpfHospede() {
      java.lang.Object ref = cpfHospede_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cpfHospede_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cpfHospede = 1;</code>
     * @return The bytes for cpfHospede.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCpfHospedeBytes() {
      java.lang.Object ref = cpfHospede_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpfHospede_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMEROQUARTO_FIELD_NUMBER = 2;
    private int numeroQuarto_;
    /**
     * <code>optional int32 numeroQuarto = 2;</code>
     * @return Whether the numeroQuarto field is set.
     */
    @java.lang.Override
    public boolean hasNumeroQuarto() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 numeroQuarto = 2;</code>
     * @return The numeroQuarto.
     */
    @java.lang.Override
    public int getNumeroQuarto() {
      return numeroQuarto_;
    }

    public static final int DATAINI_FIELD_NUMBER = 3;
    private volatile java.lang.Object dataIni_;
    /**
     * <code>optional string dataIni = 3;</code>
     * @return Whether the dataIni field is set.
     */
    @java.lang.Override
    public boolean hasDataIni() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string dataIni = 3;</code>
     * @return The dataIni.
     */
    @java.lang.Override
    public java.lang.String getDataIni() {
      java.lang.Object ref = dataIni_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataIni_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dataIni = 3;</code>
     * @return The bytes for dataIni.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataIniBytes() {
      java.lang.Object ref = dataIni_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataIni_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAFIM_FIELD_NUMBER = 4;
    private volatile java.lang.Object dataFim_;
    /**
     * <code>optional string dataFim = 4;</code>
     * @return Whether the dataFim field is set.
     */
    @java.lang.Override
    public boolean hasDataFim() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string dataFim = 4;</code>
     * @return The dataFim.
     */
    @java.lang.Override
    public java.lang.String getDataFim() {
      java.lang.Object ref = dataFim_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataFim_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dataFim = 4;</code>
     * @return The bytes for dataFim.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataFimBytes() {
      java.lang.Object ref = dataFim_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataFim_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cpfHospede_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, numeroQuarto_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataIni_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dataFim_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cpfHospede_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numeroQuarto_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataIni_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dataFim_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.quixada.ufc.si.classProto.ReservaProtos.Reserva)) {
        return super.equals(obj);
      }
      br.quixada.ufc.si.classProto.ReservaProtos.Reserva other = (br.quixada.ufc.si.classProto.ReservaProtos.Reserva) obj;

      if (hasCpfHospede() != other.hasCpfHospede()) return false;
      if (hasCpfHospede()) {
        if (!getCpfHospede()
            .equals(other.getCpfHospede())) return false;
      }
      if (hasNumeroQuarto() != other.hasNumeroQuarto()) return false;
      if (hasNumeroQuarto()) {
        if (getNumeroQuarto()
            != other.getNumeroQuarto()) return false;
      }
      if (hasDataIni() != other.hasDataIni()) return false;
      if (hasDataIni()) {
        if (!getDataIni()
            .equals(other.getDataIni())) return false;
      }
      if (hasDataFim() != other.hasDataFim()) return false;
      if (hasDataFim()) {
        if (!getDataFim()
            .equals(other.getDataFim())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCpfHospede()) {
        hash = (37 * hash) + CPFHOSPEDE_FIELD_NUMBER;
        hash = (53 * hash) + getCpfHospede().hashCode();
      }
      if (hasNumeroQuarto()) {
        hash = (37 * hash) + NUMEROQUARTO_FIELD_NUMBER;
        hash = (53 * hash) + getNumeroQuarto();
      }
      if (hasDataIni()) {
        hash = (37 * hash) + DATAINI_FIELD_NUMBER;
        hash = (53 * hash) + getDataIni().hashCode();
      }
      if (hasDataFim()) {
        hash = (37 * hash) + DATAFIM_FIELD_NUMBER;
        hash = (53 * hash) + getDataFim().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.quixada.ufc.si.classProto.ReservaProtos.Reserva prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Reserva}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Reserva)
        br.quixada.ufc.si.classProto.ReservaProtos.ReservaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.quixada.ufc.si.classProto.ReservaProtos.internal_static_tutorial_Reserva_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.quixada.ufc.si.classProto.ReservaProtos.internal_static_tutorial_Reserva_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.quixada.ufc.si.classProto.ReservaProtos.Reserva.class, br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder.class);
      }

      // Construct using br.quixada.ufc.si.classProto.ReservaProtos.Reserva.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cpfHospede_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        numeroQuarto_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        dataIni_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dataFim_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.quixada.ufc.si.classProto.ReservaProtos.internal_static_tutorial_Reserva_descriptor;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.ReservaProtos.Reserva getDefaultInstanceForType() {
        return br.quixada.ufc.si.classProto.ReservaProtos.Reserva.getDefaultInstance();
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.ReservaProtos.Reserva build() {
        br.quixada.ufc.si.classProto.ReservaProtos.Reserva result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.ReservaProtos.Reserva buildPartial() {
        br.quixada.ufc.si.classProto.ReservaProtos.Reserva result = new br.quixada.ufc.si.classProto.ReservaProtos.Reserva(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cpfHospede_ = cpfHospede_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.numeroQuarto_ = numeroQuarto_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataIni_ = dataIni_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dataFim_ = dataFim_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.quixada.ufc.si.classProto.ReservaProtos.Reserva) {
          return mergeFrom((br.quixada.ufc.si.classProto.ReservaProtos.Reserva)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.quixada.ufc.si.classProto.ReservaProtos.Reserva other) {
        if (other == br.quixada.ufc.si.classProto.ReservaProtos.Reserva.getDefaultInstance()) return this;
        if (other.hasCpfHospede()) {
          bitField0_ |= 0x00000001;
          cpfHospede_ = other.cpfHospede_;
          onChanged();
        }
        if (other.hasNumeroQuarto()) {
          setNumeroQuarto(other.getNumeroQuarto());
        }
        if (other.hasDataIni()) {
          bitField0_ |= 0x00000004;
          dataIni_ = other.dataIni_;
          onChanged();
        }
        if (other.hasDataFim()) {
          bitField0_ |= 0x00000008;
          dataFim_ = other.dataFim_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.quixada.ufc.si.classProto.ReservaProtos.Reserva parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.quixada.ufc.si.classProto.ReservaProtos.Reserva) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object cpfHospede_ = "";
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @return Whether the cpfHospede field is set.
       */
      public boolean hasCpfHospede() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @return The cpfHospede.
       */
      public java.lang.String getCpfHospede() {
        java.lang.Object ref = cpfHospede_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cpfHospede_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @return The bytes for cpfHospede.
       */
      public com.google.protobuf.ByteString
          getCpfHospedeBytes() {
        java.lang.Object ref = cpfHospede_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cpfHospede_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @param value The cpfHospede to set.
       * @return This builder for chaining.
       */
      public Builder setCpfHospede(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cpfHospede_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpfHospede() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cpfHospede_ = getDefaultInstance().getCpfHospede();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cpfHospede = 1;</code>
       * @param value The bytes for cpfHospede to set.
       * @return This builder for chaining.
       */
      public Builder setCpfHospedeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cpfHospede_ = value;
        onChanged();
        return this;
      }

      private int numeroQuarto_ ;
      /**
       * <code>optional int32 numeroQuarto = 2;</code>
       * @return Whether the numeroQuarto field is set.
       */
      @java.lang.Override
      public boolean hasNumeroQuarto() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 numeroQuarto = 2;</code>
       * @return The numeroQuarto.
       */
      @java.lang.Override
      public int getNumeroQuarto() {
        return numeroQuarto_;
      }
      /**
       * <code>optional int32 numeroQuarto = 2;</code>
       * @param value The numeroQuarto to set.
       * @return This builder for chaining.
       */
      public Builder setNumeroQuarto(int value) {
        bitField0_ |= 0x00000002;
        numeroQuarto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 numeroQuarto = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumeroQuarto() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numeroQuarto_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object dataIni_ = "";
      /**
       * <code>optional string dataIni = 3;</code>
       * @return Whether the dataIni field is set.
       */
      public boolean hasDataIni() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string dataIni = 3;</code>
       * @return The dataIni.
       */
      public java.lang.String getDataIni() {
        java.lang.Object ref = dataIni_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataIni_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dataIni = 3;</code>
       * @return The bytes for dataIni.
       */
      public com.google.protobuf.ByteString
          getDataIniBytes() {
        java.lang.Object ref = dataIni_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataIni_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dataIni = 3;</code>
       * @param value The dataIni to set.
       * @return This builder for chaining.
       */
      public Builder setDataIni(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataIni_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataIni = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataIni() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataIni_ = getDefaultInstance().getDataIni();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataIni = 3;</code>
       * @param value The bytes for dataIni to set.
       * @return This builder for chaining.
       */
      public Builder setDataIniBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataIni_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataFim_ = "";
      /**
       * <code>optional string dataFim = 4;</code>
       * @return Whether the dataFim field is set.
       */
      public boolean hasDataFim() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string dataFim = 4;</code>
       * @return The dataFim.
       */
      public java.lang.String getDataFim() {
        java.lang.Object ref = dataFim_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataFim_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dataFim = 4;</code>
       * @return The bytes for dataFim.
       */
      public com.google.protobuf.ByteString
          getDataFimBytes() {
        java.lang.Object ref = dataFim_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataFim_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dataFim = 4;</code>
       * @param value The dataFim to set.
       * @return This builder for chaining.
       */
      public Builder setDataFim(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dataFim_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataFim = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataFim() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dataFim_ = getDefaultInstance().getDataFim();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataFim = 4;</code>
       * @param value The bytes for dataFim to set.
       * @return This builder for chaining.
       */
      public Builder setDataFimBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dataFim_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Reserva)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Reserva)
    private static final br.quixada.ufc.si.classProto.ReservaProtos.Reserva DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.quixada.ufc.si.classProto.ReservaProtos.Reserva();
    }

    public static br.quixada.ufc.si.classProto.ReservaProtos.Reserva getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Reserva>
        PARSER = new com.google.protobuf.AbstractParser<Reserva>() {
      @java.lang.Override
      public Reserva parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Reserva(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Reserva> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Reserva> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.quixada.ufc.si.classProto.ReservaProtos.Reserva getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReservaBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.ReservaBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .tutorial.Reserva reserva = 1;</code>
     */
    java.util.List<br.quixada.ufc.si.classProto.ReservaProtos.Reserva> 
        getReservaList();
    /**
     * <code>repeated .tutorial.Reserva reserva = 1;</code>
     */
    br.quixada.ufc.si.classProto.ReservaProtos.Reserva getReserva(int index);
    /**
     * <code>repeated .tutorial.Reserva reserva = 1;</code>
     */
    int getReservaCount();
    /**
     * <code>repeated .tutorial.Reserva reserva = 1;</code>
     */
    java.util.List<? extends br.quixada.ufc.si.classProto.ReservaProtos.ReservaOrBuilder> 
        getReservaOrBuilderList();
    /**
     * <code>repeated .tutorial.Reserva reserva = 1;</code>
     */
    br.quixada.ufc.si.classProto.ReservaProtos.ReservaOrBuilder getReservaOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.ReservaBook}
   */
  public static final class ReservaBook extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.ReservaBook)
      ReservaBookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReservaBook.newBuilder() to construct.
    private ReservaBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReservaBook() {
      reserva_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReservaBook();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReservaBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                reserva_ = new java.util.ArrayList<br.quixada.ufc.si.classProto.ReservaProtos.Reserva>();
                mutable_bitField0_ |= 0x00000001;
              }
              reserva_.add(
                  input.readMessage(br.quixada.ufc.si.classProto.ReservaProtos.Reserva.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          reserva_ = java.util.Collections.unmodifiableList(reserva_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.quixada.ufc.si.classProto.ReservaProtos.internal_static_tutorial_ReservaBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.quixada.ufc.si.classProto.ReservaProtos.internal_static_tutorial_ReservaBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook.class, br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook.Builder.class);
    }

    public static final int RESERVA_FIELD_NUMBER = 1;
    private java.util.List<br.quixada.ufc.si.classProto.ReservaProtos.Reserva> reserva_;
    /**
     * <code>repeated .tutorial.Reserva reserva = 1;</code>
     */
    @java.lang.Override
    public java.util.List<br.quixada.ufc.si.classProto.ReservaProtos.Reserva> getReservaList() {
      return reserva_;
    }
    /**
     * <code>repeated .tutorial.Reserva reserva = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends br.quixada.ufc.si.classProto.ReservaProtos.ReservaOrBuilder> 
        getReservaOrBuilderList() {
      return reserva_;
    }
    /**
     * <code>repeated .tutorial.Reserva reserva = 1;</code>
     */
    @java.lang.Override
    public int getReservaCount() {
      return reserva_.size();
    }
    /**
     * <code>repeated .tutorial.Reserva reserva = 1;</code>
     */
    @java.lang.Override
    public br.quixada.ufc.si.classProto.ReservaProtos.Reserva getReserva(int index) {
      return reserva_.get(index);
    }
    /**
     * <code>repeated .tutorial.Reserva reserva = 1;</code>
     */
    @java.lang.Override
    public br.quixada.ufc.si.classProto.ReservaProtos.ReservaOrBuilder getReservaOrBuilder(
        int index) {
      return reserva_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < reserva_.size(); i++) {
        output.writeMessage(1, reserva_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < reserva_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, reserva_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook)) {
        return super.equals(obj);
      }
      br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook other = (br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook) obj;

      if (!getReservaList()
          .equals(other.getReservaList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getReservaCount() > 0) {
        hash = (37 * hash) + RESERVA_FIELD_NUMBER;
        hash = (53 * hash) + getReservaList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ReservaBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.ReservaBook)
        br.quixada.ufc.si.classProto.ReservaProtos.ReservaBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.quixada.ufc.si.classProto.ReservaProtos.internal_static_tutorial_ReservaBook_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.quixada.ufc.si.classProto.ReservaProtos.internal_static_tutorial_ReservaBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook.class, br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook.Builder.class);
      }

      // Construct using br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getReservaFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (reservaBuilder_ == null) {
          reserva_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          reservaBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.quixada.ufc.si.classProto.ReservaProtos.internal_static_tutorial_ReservaBook_descriptor;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook getDefaultInstanceForType() {
        return br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook.getDefaultInstance();
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook build() {
        br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook buildPartial() {
        br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook result = new br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook(this);
        int from_bitField0_ = bitField0_;
        if (reservaBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            reserva_ = java.util.Collections.unmodifiableList(reserva_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.reserva_ = reserva_;
        } else {
          result.reserva_ = reservaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook) {
          return mergeFrom((br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook other) {
        if (other == br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook.getDefaultInstance()) return this;
        if (reservaBuilder_ == null) {
          if (!other.reserva_.isEmpty()) {
            if (reserva_.isEmpty()) {
              reserva_ = other.reserva_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureReservaIsMutable();
              reserva_.addAll(other.reserva_);
            }
            onChanged();
          }
        } else {
          if (!other.reserva_.isEmpty()) {
            if (reservaBuilder_.isEmpty()) {
              reservaBuilder_.dispose();
              reservaBuilder_ = null;
              reserva_ = other.reserva_;
              bitField0_ = (bitField0_ & ~0x00000001);
              reservaBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getReservaFieldBuilder() : null;
            } else {
              reservaBuilder_.addAllMessages(other.reserva_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<br.quixada.ufc.si.classProto.ReservaProtos.Reserva> reserva_ =
        java.util.Collections.emptyList();
      private void ensureReservaIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          reserva_ = new java.util.ArrayList<br.quixada.ufc.si.classProto.ReservaProtos.Reserva>(reserva_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.quixada.ufc.si.classProto.ReservaProtos.Reserva, br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder, br.quixada.ufc.si.classProto.ReservaProtos.ReservaOrBuilder> reservaBuilder_;

      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public java.util.List<br.quixada.ufc.si.classProto.ReservaProtos.Reserva> getReservaList() {
        if (reservaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reserva_);
        } else {
          return reservaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public int getReservaCount() {
        if (reservaBuilder_ == null) {
          return reserva_.size();
        } else {
          return reservaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public br.quixada.ufc.si.classProto.ReservaProtos.Reserva getReserva(int index) {
        if (reservaBuilder_ == null) {
          return reserva_.get(index);
        } else {
          return reservaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public Builder setReserva(
          int index, br.quixada.ufc.si.classProto.ReservaProtos.Reserva value) {
        if (reservaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReservaIsMutable();
          reserva_.set(index, value);
          onChanged();
        } else {
          reservaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public Builder setReserva(
          int index, br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder builderForValue) {
        if (reservaBuilder_ == null) {
          ensureReservaIsMutable();
          reserva_.set(index, builderForValue.build());
          onChanged();
        } else {
          reservaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public Builder addReserva(br.quixada.ufc.si.classProto.ReservaProtos.Reserva value) {
        if (reservaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReservaIsMutable();
          reserva_.add(value);
          onChanged();
        } else {
          reservaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public Builder addReserva(
          int index, br.quixada.ufc.si.classProto.ReservaProtos.Reserva value) {
        if (reservaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReservaIsMutable();
          reserva_.add(index, value);
          onChanged();
        } else {
          reservaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public Builder addReserva(
          br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder builderForValue) {
        if (reservaBuilder_ == null) {
          ensureReservaIsMutable();
          reserva_.add(builderForValue.build());
          onChanged();
        } else {
          reservaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public Builder addReserva(
          int index, br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder builderForValue) {
        if (reservaBuilder_ == null) {
          ensureReservaIsMutable();
          reserva_.add(index, builderForValue.build());
          onChanged();
        } else {
          reservaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public Builder addAllReserva(
          java.lang.Iterable<? extends br.quixada.ufc.si.classProto.ReservaProtos.Reserva> values) {
        if (reservaBuilder_ == null) {
          ensureReservaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, reserva_);
          onChanged();
        } else {
          reservaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public Builder clearReserva() {
        if (reservaBuilder_ == null) {
          reserva_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          reservaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public Builder removeReserva(int index) {
        if (reservaBuilder_ == null) {
          ensureReservaIsMutable();
          reserva_.remove(index);
          onChanged();
        } else {
          reservaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder getReservaBuilder(
          int index) {
        return getReservaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public br.quixada.ufc.si.classProto.ReservaProtos.ReservaOrBuilder getReservaOrBuilder(
          int index) {
        if (reservaBuilder_ == null) {
          return reserva_.get(index);  } else {
          return reservaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public java.util.List<? extends br.quixada.ufc.si.classProto.ReservaProtos.ReservaOrBuilder> 
           getReservaOrBuilderList() {
        if (reservaBuilder_ != null) {
          return reservaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reserva_);
        }
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder addReservaBuilder() {
        return getReservaFieldBuilder().addBuilder(
            br.quixada.ufc.si.classProto.ReservaProtos.Reserva.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder addReservaBuilder(
          int index) {
        return getReservaFieldBuilder().addBuilder(
            index, br.quixada.ufc.si.classProto.ReservaProtos.Reserva.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Reserva reserva = 1;</code>
       */
      public java.util.List<br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder> 
           getReservaBuilderList() {
        return getReservaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.quixada.ufc.si.classProto.ReservaProtos.Reserva, br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder, br.quixada.ufc.si.classProto.ReservaProtos.ReservaOrBuilder> 
          getReservaFieldBuilder() {
        if (reservaBuilder_ == null) {
          reservaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              br.quixada.ufc.si.classProto.ReservaProtos.Reserva, br.quixada.ufc.si.classProto.ReservaProtos.Reserva.Builder, br.quixada.ufc.si.classProto.ReservaProtos.ReservaOrBuilder>(
                  reserva_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          reserva_ = null;
        }
        return reservaBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.ReservaBook)
    }

    // @@protoc_insertion_point(class_scope:tutorial.ReservaBook)
    private static final br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook();
    }

    public static br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ReservaBook>
        PARSER = new com.google.protobuf.AbstractParser<ReservaBook>() {
      @java.lang.Override
      public ReservaBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReservaBook(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReservaBook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReservaBook> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.quixada.ufc.si.classProto.ReservaProtos.ReservaBook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Reserva_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Reserva_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ReservaBook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ReservaBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/reserva.proto\022\010tutorial\"U\n\007Reser" +
      "va\022\022\n\ncpfHospede\030\001 \001(\t\022\024\n\014numeroQuarto\030\002" +
      " \001(\005\022\017\n\007dataIni\030\003 \001(\t\022\017\n\007dataFim\030\004 \001(\t\"1" +
      "\n\013ReservaBook\022\"\n\007reserva\030\001 \003(\0132\021.tutoria" +
      "l.ReservaB-\n\034br.quixada.ufc.si.classProt" +
      "oB\rReservaProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Reserva_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Reserva_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Reserva_descriptor,
        new java.lang.String[] { "CpfHospede", "NumeroQuarto", "DataIni", "DataFim", });
    internal_static_tutorial_ReservaBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_ReservaBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ReservaBook_descriptor,
        new java.lang.String[] { "Reserva", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
